import test from 'node:test'
import assert from 'node:assert/strict'
import * as T from '../lib/game/scene-data'
import { SoldierBatch, vehicleGeometry } from '../lib/game/unit-models'
import { BattlefieldAudio } from '../lib/game/audio'
import { initialState, type Soldier, type Role } from '../lib/game/types'
const soldier:Soldier={id:'test:0',x:0,y:0,status:'active',stance:'stand',action:'walk',heading:0,aim:1,shotAt:-10,since:0}
test('walking bends knees and independently rotates the upper torso',()=>{const batch=new SoldierBatch(new T.Scene(),'BLU',new T.MeshBasicMaterial());batch.begin();batch.pose(soldier,'RIFLE',.2,0);assert.notEqual(batch.knees[0].rotation.x+batch.knees[1].rotation.x,0);assert.ok(Math.abs(batch.torso.rotation.z+1)<.001);batch.end(true);assert.equal(batch.parts.get('thigh')!.count,2);assert.equal(batch.parts.get('rifle')!.count,1);assert.equal(batch.parts.get('launcher')!.count,0)})
test('crouch lowers pelvis; prone and death produce horizontal bodies',()=>{const batch=new SoldierBatch(new T.Scene(),'RED',new T.MeshBasicMaterial());batch.begin();batch.pose({...soldier,stance:'crouch'},'MG',2,0);assert.ok(batch.pelvis.position.z<.7);assert.ok(batch.knees[0].rotation.x < -1);assert.ok(batch.hips[0].rotation.x>0);batch.pose({...soldier,stance:'prone'},'MG',2,0);assert.ok(Math.abs(batch.root.rotation.x)>1.5);assert.ok(Math.abs(batch.weapon.rotation.x-Math.PI/2)<.01);batch.pose({...soldier,status:'dead'},'AT',2,0);assert.ok(Math.abs(batch.root.rotation.x)>1.5)})
test('all live vehicle classes and their attachments produce finite geometry',()=>{for(const role of ['TANK','APC','IFV','CANNON_APC','JET','ATTACK_HELI'] as Role[]){const g=vehicleGeometry(role,'BLU');assert.ok(g.getAttribute('position').count>0);assert.ok([...g.getAttribute('position').array].every(Number.isFinite));g.dispose()}})
test('audio deduplicates shot events and does not replay paused backlog',()=>{const engine=new BattlefieldAudio(),state=initialState();state.units=[];state.events=[];engine.enabled=true;const calls:string[]=[];engine.play=(key:string)=>{calls.push(key);return null};const original=Object.getOwnPropertyDescriptor(globalThis,'document');Object.defineProperty(globalThis,'document',{configurable:true,value:{hidden:false}})
  try{state.shots=[{id:1,time:0,unit:'test',side:'BLU',weapon:'rifle',start:{x:0,y:0,z:1},end:{x:10,y:0,z:1},speed:600,size:.05,blast:0,sound:'RIFLE_FIRE',spotted:false}];engine.update(state,'OBS',{x:0,y:0});engine.update(state,'OBS',{x:0,y:0});assert.equal(calls.length,1);state.paused=true;state.shots.push({...state.shots[0],id:2});engine.update(state,'OBS',{x:0,y:0});state.paused=false;engine.update(state,'OBS',{x:0,y:0});assert.equal(calls.length,1);state.shots.push({...state.shots[0],id:3,side:'RED'});engine.update(state,'BLU',{x:0,y:0});assert.equal(calls.length,1)}finally{if(original)Object.defineProperty(globalThis,'document',original);else Reflect.deleteProperty(globalThis,'document')}
})
