import test from 'node:test'
import assert from 'node:assert/strict'
import { Visibility } from '../lib/game/visibility'
import { damageFor, weaponFor, WEAPONS } from '../lib/game/weapons'
import { battleFixture as initialState } from './fixtures'
import { lngLat, prepareUnit, type GeometryPacket, type Role } from '../lib/game/types'
import { canSee, resolveCombat } from '../lib/game/combat'
import { updateSoldiers } from '../lib/game/behaviors'
import { Navigation } from '../lib/game/navigation'
import { DEFAULT_BANK, parseSoundBank } from '../lib/game/sfx-schema'
import { BattlefieldAudio } from '../lib/game/audio'
function packet():GeometryPacket{return {complete:true,version:1,features:[],terrain:{x:-1800,y:-1100,step:50,width:73,height:45,values:Array(73*45).fill(0)}}}
function wall(x=100,roof=5){return {key:'wall',water:false,roof,rings:[[[x,-40],[x+.15,-40],[x+.15,40],[x,40],[x,-40]].map(([x,y])=>lngLat({x,y}))]}}
function fixture(distance=550){const state=initialState();state.units=[state.units[0],state.units.find(u=>u.side==='RED'&&u.role==='RIFLE')!];state.units.forEach((u,i)=>{u.x=i*distance;u.y=0;u.members=1;u.maxMembers=1;prepareUnit(u);u.soldiers!.forEach(s=>{s.x=u.x;s.y=0})});const v=new Visibility();v.import(packet());return {state,v}}
test('thin walls block rays; roofs can be seen over; water is transparent',()=>{const v=new Visibility(),p=packet();p.features=[wall()];v.import(p);assert.equal(v.ray({x:0,y:0,z:1.6},{x:200,y:0,z:1.6}).kind,'building');assert.equal(v.ray({x:0,y:0,z:6},{x:200,y:0,z:6}).kind,'clear');const water=packet();water.features=[{...wall(),water:true}];const w=new Visibility();w.import(water);assert.equal(w.ray({x:0,y:0,z:1},{x:200,y:0,z:1}).kind,'clear')})
test('polygon holes remain open while exterior shells obstruct',()=>{const v=new Visibility(),p=packet();p.features=[{key:'courtyard',water:false,roof:5,rings:[[[0,0],[100,0],[100,100],[0,100],[0,0]],[[10,10],[90,10],[90,90],[10,90],[10,10]]].map(r=>r.map(([x,y])=>lngLat({x,y})))}];v.import(p);assert.equal(v.ray({x:20,y:50,z:1},{x:80,y:50,z:1}).kind,'clear');assert.equal(v.ray({x:20,y:50,z:1},{x:120,y:50,z:1}).kind,'building')})
test('unknown coverage withholds fire and terrain blocks low rays',()=>{const v=new Visibility();assert.equal(v.ray({x:0,y:0,z:1},{x:10,y:0,z:1}).kind,'unknown');const p=packet();p.terrain.values.fill(10);v.import(p);assert.equal(v.ray({x:0,y:0,z:1},{x:100,y:0,z:1}).kind,'terrain')})
test('rifle acquires and shoots at 550m but never beyond 600m',()=>{const {state,v}=fixture();assert.equal(canSee(state.units[0],state.units[1],v,state),true);let id=0;resolveCombat(state,v,()=>.5,()=>++id);assert.ok(state.shots.length>0);assert.ok(state.units[1].hp<100);const far=fixture(610);resolveCombat(far.state,far.v,()=>.5,()=>++id);assert.equal(far.state.shots.length,0)})
test('teammate spotting does not grant shooting through buildings',()=>{const {state,v}=fixture();const p=packet();p.features=[wall()];v.import(p);state.units.forEach(u=>u.spotted=true);let id=0;resolveCombat(state,v,()=>.5,()=>++id);assert.equal(state.shots.length,0);assert.equal(state.units[1].hp,100)})
test('visible head cannot authorize blocked muzzle',()=>{const {state,v}=fixture(200);const p=packet();p.features=[wall(100,1.5)];v.import(p);assert.ok(canSee(state.units[0],state.units[1],v,state));let id=0;resolveCombat(state,v,()=>.5,()=>++id);assert.equal(state.shots.length,0)})
test('strict armor damage whitelist includes tank IFV cannon APC and aircraft',()=>{for(const role of ['RIFLE','SCOUT','MG','APC','MORTAR','MEDIC','ENGINEER'] as Role[])assert.equal(damageFor(weaponFor(role)!,{role:'TANK'},100),0,role);for(const role of ['AT','TANK','IFV','CANNON_APC','JET','ATTACK_HELI'] as Role[])assert.ok(damageFor(weaponFor(role)!,{role:'TANK'},100)>0,role);assert.ok(WEAPONS.mg.size>WEAPONS.rifle.size);assert.equal(WEAPONS.mg.blast,0)})
test('raycast hits the first body, not the selected body beyond it',()=>{const {state,v}=fixture(550);const front=structuredClone(state.units[1]);front.id='front';front.x=200;front.soldiers![0].id='front:0';front.soldiers![0].x=200;front.ammo=0;state.units.push(front);state.units[1].ammo=0;let id=0;resolveCombat(state,v,()=>.5,()=>++id);assert.ok(front.hp<100);assert.equal(state.units[1].hp,100)})
test('smoke grows, blocks sight, and expires',()=>{const {state,v}=fixture(100);state.smokes=[{id:1,side:'BLU',x:50,y:0,z:0,time:0,expires:25,from:{x:0,y:0,z:1}}];state.time=5;assert.equal(canSee(state.units[0],state.units[1],v,state),false);state.time=26;assert.equal(canSee(state.units[0],state.units[1],v,state),true)})
test('rescue is interrupted when the downed target dies',()=>{const {state,v}=fixture();const rescuer=state.units[0].soldiers![0],body=structuredClone(rescuer);body.id='body';body.status='dead';rescuer.rescue='body';state.units[0].soldiers!.push(body);updateSoldiers(state,v,new Navigation(),()=>1);assert.equal(rescuer.rescue,undefined)})
test('dead bodies do not expire before transfer to persistent records',()=>{const {state,v}=fixture();state.time=200;const unit=state.units[0],soldier=unit.soldiers![0];unit.soldiers=[soldier,...Array.from({length:300},(_,i)=>({...soldier,id:`dead-${i}`,status:'dead' as const,since:190+i/100})),{...soldier,id:'expired',status:'dead',since:0},{...soldier,id:'downed',status:'downed',since:199}];updateSoldiers(state,v,new Navigation(),()=>1);assert.equal(unit.soldiers.filter(s=>s.status==='dead').length,301);assert.ok(unit.soldiers.some(s=>s.id==='downed'));assert.ok(unit.soldiers.some(s=>s.id==='expired'));assert.equal(unit.members,1)})
test('suppression interrupts rescue without reviving or losing the casualty',()=>{const {state,v}=fixture();const unit=state.units[0],rescuer=unit.soldiers![0];unit.soldiers!.push({...rescuer,id:'wounded',status:'downed'});rescuer.rescue='wounded';unit.suppression=.95;updateSoldiers(state,v,new Navigation(),()=>1);assert.equal(rescuer.rescue,undefined);assert.equal(unit.soldiers![1].status,'downed');assert.equal(unit.members,1)})
test('all supplied presets validate including outputs above one and speed ratios below one',()=>{const result=parseSoundBank(JSON.stringify(DEFAULT_BANK));assert.equal(result.replaced,18);assert.deepEqual(result.bank,DEFAULT_BANK);assert.ok(result.bank.FIGHTER_JET_ENGINE.speedPitchMax<1)})
test('partial sound updates are atomic and malformed banks retain last working sounds',()=>{const engine=new BattlefieldAudio(),old=engine.bank;assert.throws(()=>engine.import('{','bad_sfx.json'));assert.equal(engine.bank,old);assert.throws(()=>parseSoundBank(JSON.stringify({RIFLE_FIRE:{...DEFAULT_BANK.RIFLE_FIRE,output:Infinity}})));assert.throws(()=>parseSoundBank(' '.repeat(300000)));assert.throws(()=>parseSoundBank('{"__proto__":{}}'));assert.equal(parseSoundBank(JSON.stringify({RIFLE_FIRE:DEFAULT_BANK.RIFLE_FIRE})).retained,17)})
