import test from 'node:test'
import assert from 'node:assert/strict'
import * as T from 'three'
import { battleFixture as initialState } from './fixtures'
import { stockTotal, BASES, AIRBASES, prepareUnit, type GeometryPacket } from '../lib/game/types'
import { Navigation } from '../lib/game/navigation'
import { Visibility } from '../lib/game/visibility'
import { sectorKey, sectorOrigin } from '../lib/game/theater'
import { assignTransports, updateTransports } from '../lib/game/transport'
import { updateSupplyMissions } from '../lib/game/logistics'
import { deployJammer, updateJammers, jammed } from '../lib/game/electronic-warfare'
import { recordCasualties } from '../lib/game/casualties'
import { resolveCombat, canSee } from '../lib/game/combat'
import { eligible, WEAPONS } from '../lib/game/weapons'
import { SoldierBatch, vehicleGeometry } from '../lib/game/unit-models'
import { createAircraft, disposeModel } from '../lib/game/aircraft-models'
import { createSupportModel } from '../lib/game/support-models'
const sector=(x:number,y:number):GeometryPacket=>({sector:sectorKey({x,y}),complete:true,version:1,features:[],terrain:{...sectorOrigin(sectorKey({x,y})),step:50,width:41,height:41,values:Array(1681).fill(0)}})
test('sector navigation holds unknown areas without clamping city endpoints',()=>{const nav=new Navigation();nav.strict=true;assert.equal(nav.clear(BASES.RED,BASES.RED),false);nav.packet(sector(BASES.RED.x,BASES.RED.y));assert.equal(nav.clear(BASES.RED,BASES.RED),true);assert.deepEqual(nav.nearest(BASES.BLU),BASES.BLU);assert.equal(nav.clear(BASES.BLU,BASES.BLU),false);assert.ok(nav.strategic(BASES.RED,BASES.BLU).length>10)})
test('visibility rejects an unknown gap between covered ray endpoints',()=>{const v=new Visibility();v.import(sector(1,1));v.import(sector(4001,1));assert.equal(v.ray({x:100,y:100,z:100},{x:4100,y:100,z:100}).kind,'unknown');v.import(sector(2001,1));assert.equal(v.ray({x:100,y:100,z:100},{x:4100,y:100,z:100}).kind,'clear')})
test('transport reservations are atomic and actual troops disembark',()=>{const state=initialState(),s=state.units.find(u=>u.role==='RIFLE')!,c=state.units.find(u=>u.role==='TROOP_TRUCK')!,nav=new Navigation();state.units=[s,c];s.x=BASES.BLU.x;s.y=BASES.BLU.y;s.target='A';state.objectives[0].x=s.x+1200;state.objectives[0].y=s.y;c.x=s.x;c.y=s.y;c.altitude=0;assignTransports(state);assignTransports(state);assert.deepEqual(c.transport?.passengers,[s.id]);for(let i=0;i<140;i++){state.time=i*.05;updateTransports(state,nav)}assert.equal(s.carrier,c.id);assert.equal(canSee(s,c,new Visibility(),state),false);for(let i=140;i<2000;i++){state.time=i*.05;updateTransports(state,nav)}assert.equal(s.carrier,undefined);assert.equal(s.mission,'CAPTURE');assert.equal(s.members,4);assert.ok(Math.hypot(s.x-state.objectives[0].x,s.y-state.objectives[0].y)<50)})
test('aircraft loss kills embarked passengers exactly once and leaves a grounded wreck',()=>{const state=initialState(),s=state.units[0],c=state.units.find(u=>u.role==='TRANSPORT_HELI')!;state.units=[s,c];s.carrier=c.id;c.transport={phase:'transit',since:0,passengers:[s.id]};c.hp=0;c.altitude=90;const nav=new Navigation(),v=new Visibility();recordCasualties(state,nav,v,()=>.99);assert.equal(s.members,0);assert.equal(state.forces.BLU.casualties,4);assert.equal(state.casualties.length,5);for(let i=1;i<400;i++){state.time=i*.05;recordCasualties(state,nav,v,()=>.99)}assert.equal(state.forces.BLU.casualties,4);assert.equal(state.casualties.find(w=>w.id===c.id)!.altitude,0);state.time=20000;recordCasualties(state,nav,v,()=>.99);assert.equal(state.casualties.length,5)})
test('ground transport can produce validated survivors',()=>{const state=initialState(),s=state.units[0],c=state.units.find(u=>u.role==='TROOP_TRUCK')!;state.units=[s,c];s.carrier=c.id;c.hp=0;recordCasualties(state,new Navigation(),new Visibility(),()=>.99);assert.equal(s.members,4);assert.equal(s.carrier,undefined);assert.equal(state.forces.BLU.casualties,0)})
test('cargo plane lands then credits its manifest once at unloading',()=>{const state=initialState(),plane=state.units.find(u=>u.role==='CARGO_PLANE')!;state.units=[plane];plane.y-=2100;plane.transport={phase:'approach',since:0,manifest:{fuel:300,ammo:300,repair:300},cargo:900};const nav=new Navigation(),phases=new Set<string>();let landed=false;for(let i=0;i<6000;i++){state.time=i*.05;updateSupplyMissions(state,nav);phases.add(plane.transport!.phase);if(plane.transport!.phase==='rollout'){assert.ok((plane.altitude||0)<=1);landed=true}if(stockTotal(state.depots.BLU.pending)===900)break}assert.ok(landed);assert.ok(phases.has('taxi-in'));assert.equal(stockTotal(state.depots.BLU.pending),900);updateSupplyMissions(state,nav);assert.equal(stockTotal(state.depots.BLU.pending),900);assert.equal(plane.transport!.cargo,0)})
test('forklift conserves pending, carried and available inventory',()=>{const state=initialState(),fork=state.units.find(u=>u.role==='FORKLIFT')!;Object.assign(fork,AIRBASES.BLU);fork.external=true;state.units=[fork];state.depots.BLU.pending={fuel:100,ammo:100,repair:100};const nav=new Navigation();for(let i=0;i<2500;i++){state.time=i*.05;updateSupplyMissions(state,nav);const d=state.depots.BLU;assert.ok(Math.abs(stockTotal(d.airfield)+stockTotal(d.pending)+stockTotal(d.mob)+state.units.filter(u=>u.side==='BLU').reduce((n,u)=>n+(u.transport?.cargo||0),0)-300)<1e-6)}assert.ok(stockTotal(state.depots.BLU.airfield)>0)})
test('heavy lift debits source stock and credits destination at unload',()=>{const state=initialState(),heli=state.units.find(u=>u.role==='HEAVY_LIFT_HELI')!;state.units=[heli];state.depots.BLU.airfield={fuel:200,ammo:200,repair:200};const nav=new Navigation();let carrying=false;for(let i=0;i<12000;i++){state.time=i*.05;updateSupplyMissions(state,nav);if(heli.transport?.cargo)carrying=true;const d=state.depots.BLU;assert.ok(Math.abs(stockTotal(d.airfield)+stockTotal(d.mob)+state.units.filter(u=>u.side==='BLU').reduce((n,u)=>n+(u.transport?.cargo||0),0)-600)<1e-6);if(heli.servicing)break}assert.ok(carrying);assert.ok(stockTotal(state.depots.BLU.mob)>0);assert.equal(heli.transport!.cargo,0)})
test('jammer validates builder, prevents duplicate builds, activates only after construction',()=>{const state=initialState(),builder=state.units[0],nav=new Navigation();state.units=[builder];const sp=state.forces.BLU.sp;assert.equal(deployJammer(state,nav,builder.id,'RED'),'An active logistics team or squad leader is required.');assert.equal(deployJammer(state,nav,builder.id,'BLU'),'');assert.ok(deployJammer(state,nav,builder.id,'BLU'));assert.equal(state.forces.BLU.sp,sp-200);const j=state.units.at(-1)!;assert.ok(j.construction);state.time=16;updateJammers(state,nav);assert.equal(j.construction,undefined);assert.equal(j.mission,'JAMMING')})
test('jammer denies only hostile UAV reconnaissance, not ground observers',()=>{const state=initialState(),uav=state.units.find(u=>u.role==='RECON_UAV')!,target=state.units.find(u=>u.side==='RED'&&u.role==='RIFLE')!,ground=state.units[0];Object.assign(uav,{x:100,y:100,altitude:90});Object.assign(target,{x:400,y:100});Object.assign(ground,{x:100,y:100});prepareUnit(target);prepareUnit(ground);const jammer={...target,id:'j',role:'UAV_JAMMER' as const,x:450,y:100,soldiers:[],construction:undefined};state.units=[uav,target,ground,jammer];const v=new Visibility();v.import(sector(1,1));assert.equal(jammed(uav,target,state),true);assert.equal(canSee(uav,target,v,state),false);assert.equal(canSee(ground,target,v,state),true);jammer.side='BLU';assert.equal(jammed(uav,target,state),false);jammer.side='RED';jammer.hp=0;assert.equal(jammed(uav,target,state),false)})
test('AA locks air targets and damage waits until missile impact',()=>{const state=initialState(),aa=state.units.find(u=>u.role==='AA_TEAM')!,jet=state.units.find(u=>u.role==='JET'&&u.side==='RED')!;state.units=[aa,jet];Object.assign(aa,{x:100,y:100});Object.assign(jet,{x:600,y:100,ammo:0,altitude:100});prepareUnit(aa);const v=new Visibility();v.import(sector(1,1));let id=0;resolveCombat(state,v,()=>.5,()=>++id);assert.equal(state.missiles.length,0);state.time=2.6;resolveCombat(state,v,()=>.5,()=>++id);assert.equal(state.missiles.length,1);assert.equal(jet.hp,100);state.time=state.missiles[0].due+.01;resolveCombat(state,v,()=>.5,()=>++id);assert.equal(jet.hp,35);assert.equal(aa.ammo,75);assert.equal(eligible(WEAPONS.aa,{role:'TANK'}),false)})
test('knees never hyperextend throughout a walking cycle',()=>{const scene=new T.Scene(),batch=new SoldierBatch(scene,'BLU',new T.MeshBasicMaterial());for(let i=0;i<=120;i++){batch.pose({id:'test',x:0,y:0,status:'active',stance:'stand',action:'walk',heading:0,aim:0,since:0,shotAt:-10},'RIFLE',i/120,0);assert.ok(batch.knees.every(k=>k.rotation.x<=0))}disposeModel(scene)})
test('requested assets have distinguishable silhouettes and articulated parts',()=>{const apc=vehicleGeometry('APC','BLU'),ifv=vehicleGeometry('IFV','BLU');assert.notDeepEqual(apc.getAttribute('position').array,ifv.getAttribute('position').array);apc.dispose();ifv.dispose();const forklift=createSupportModel('FORKLIFT','BLU'),heavy=createAircraft('HEAVY_LIFT_HELI','BLU'),cargo=createAircraft('CARGO_PLANE','BLU');assert.ok(forklift.getObjectByName('fork-carriage'));assert.ok(heavy.getObjectByName('rear-rotor'));assert.ok(heavy.getObjectByName('sling-cargo'));assert.ok(cargo.getObjectByName('cargo-ramp'));for(const o of [forklift,heavy,cargo])disposeModel(o)})
