'use client'

import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { Download, Plus, RotateCcw, Trash2, Upload } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { assetPath } from '@/lib/asset-path'
import { BUILDING_MODULE, normalizeBuildingPreset, parseBuildingPresets, type BuildingPreset, type BuildingType } from '@/lib/game/building-system'
import { BuildingViewport } from './building-viewport'

const empty: BuildingPreset = { id: 'custom-building', name: 'Custom building', type: 'residential', width: 4, depth: 3, floors: 3, seed: 3701, roof: 'auto' }
const download = (presets: BuildingPreset[]) => { const url = URL.createObjectURL(new Blob([JSON.stringify(presets, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = '_buildings.json'; link.click(); URL.revokeObjectURL(url) }

function FootprintEditor({ value, onChange }: { value: BuildingPreset; onChange: (next: BuildingPreset) => void }) {
  const host = useRef<SVGSVGElement>(null), start = useRef<{ x: number; y: number } | null>(null)
  const cell = (event: PointerEvent<SVGSVGElement>) => { const rect = host.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(15, Math.floor((event.clientX - rect.left) / rect.width * 16))), y: Math.max(0, Math.min(15, Math.floor((event.clientY - rect.top) / rect.height * 16))) } }
  const update = (event: PointerEvent<SVGSVGElement>) => { if (!start.current) return; const end = cell(event); onChange({ ...value, width: Math.abs(end.x - start.current.x) + 1, depth: Math.abs(end.y - start.current.y) + 1 }) }
  return <svg ref={host} viewBox="0 0 320 320" className="aspect-square w-full touch-none rounded-md border border-border bg-[#101c2a]" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); start.current = cell(e); update(e) }} onPointerMove={update} onPointerUp={e => { update(e); start.current = null }} aria-label="Drag to set building footprint">
    <defs><pattern id="building-grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#32465a" strokeWidth="1" /></pattern></defs><rect width="320" height="320" fill="url(#building-grid)" />
    <rect x="10" y="10" width={value.width * 20} height={value.depth * 20} fill="#54b7ff22" stroke="#54b7ff" strokeWidth="2" /><text x="18" y={Math.min(306, value.depth * 20 + 30)} fill="#91a6b8" fontSize="12">{value.width * BUILDING_MODULE} × {value.depth * BUILDING_MODULE} m</text>
  </svg>
}

export function BuildingEditor() {
  const [draft, setDraft] = useState<BuildingPreset>(empty), [presets, setPresets] = useState<BuildingPreset[]>([]), [error, setError] = useState('')
  useEffect(() => { const saved = localStorage.getItem('grid-command-buildings'); if (saved) { try { setPresets(parseBuildingPresets(JSON.parse(saved))); return } catch {} } fetch(assetPath('/_buildings.json')).then(r => r.json()).then(value => setPresets(parseBuildingPresets(value))).catch(() => setPresets([])) }, [])
  const save = (next: BuildingPreset[]) => { setPresets(next); localStorage.setItem('grid-command-buildings', JSON.stringify(next)) }
  const select = (preset: BuildingPreset) => { setDraft({ ...preset }); setError('') }
  const exists = presets.some(p => p.id === draft.id)
  const persist = () => { const preset = normalizeBuildingPreset({ ...draft, id: exists ? draft.id : `${draft.type}-${Date.now()}`, name: draft.name || `${draft.type} building` }); save(exists ? presets.map(item => item.id === preset.id ? preset : item) : [...presets, preset]); select(preset) }
  return <div className="flex h-full min-h-0 w-full flex-col overflow-hidden bg-background"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-6 py-4"><div><h1 className="text-xl font-medium">Building Designer</h1><p className="pt-1 text-sm text-muted-foreground">Drag a footprint, raise floors, and save deterministic modular presets.</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><Upload size={15} />Import JSON<input className="sr-only" type="file" accept="application/json,.json" onChange={async e => { const file=e.target.files?.[0]; if(!file)return; try{const next=parseBuildingPresets(JSON.parse(await file.text()));save(next);select(next[0]||empty);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Invalid building preset file.')}e.target.value='' }} /></label><Button variant="outline" onClick={()=>download(presets)}><Download />Export JSON</Button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-1 overflow-y-auto lg:grid-cols-[300px_minmax(360px,1fr)_320px]"><aside className="border-r border-border p-4"><div className="mb-3 flex items-center justify-between"><span className="eyebrow">PRESETS</span><Button size="icon-sm" variant="ghost" aria-label="New preset" onClick={()=>setDraft({...empty,id:`draft-${Date.now()}`,seed:Math.floor(Math.random()*99999)})}><Plus /></Button></div><div className="flex flex-col gap-2">{presets.map(p=><button key={p.id} onClick={()=>select(p)} className={`rounded-md border px-3 py-3 text-left ${p.id===draft.id?'border-primary bg-primary/10':'border-border hover:bg-secondary'}`}><span className="block text-sm font-medium">{p.name}</span><span className="text-xs text-muted-foreground">{p.type} · {p.width}×{p.depth} · {p.floors}F</span></button>)}</div></aside>
      <main className="relative flex min-h-[520px] items-center justify-center p-5"><BuildingViewport preset={draft} /></main>
      <aside className="border-l border-border p-5"><div className="flex flex-col gap-4"><label className="text-sm">Name<input className="mt-2 w-full rounded-md border border-border bg-background px-3 py-2" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="text-sm">Building type<select className="settings-select mt-2 w-full" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as BuildingType})}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="industrial">Industrial</option></select></label><div><span className="text-sm">Footprint · drag the grid</span><div className="mt-2"><FootprintEditor value={draft} onChange={setDraft}/></div></div><label className="text-sm">Floors · {draft.floors}<input className="mt-2 w-full" type="range" min="1" max="40" value={draft.floors} onChange={e=>setDraft({...draft,floors:Number(e.target.value)})}/></label><label className="text-sm">Roof<select className="settings-select mt-2 w-full" value={draft.roof} onChange={e=>setDraft({...draft,roof:e.target.value as BuildingPreset['roof']})}><option value="auto">Deterministic auto</option><option value="flat">Flat</option><option value="gable">Angled</option></select></label><label className="text-sm">Variation seed<input className="mt-2 w-full rounded-md border border-border bg-background px-3 py-2 font-mono" type="number" value={draft.seed} onChange={e=>setDraft({...draft,seed:Number(e.target.value)})}/></label><div className="flex flex-wrap gap-2"><Button onClick={persist}><Plus />{exists?'Save preset':'Add preset'}</Button><Button variant="outline" onClick={()=>setDraft({...draft,seed:draft.seed+1})}><RotateCcw />Reroll</Button>{exists&&<Button variant="destructive" size="icon" aria-label="Delete preset" onClick={()=>{const next=presets.filter(p=>p.id!==draft.id);save(next);select(next[0]||empty)}}><Trash2 /></Button>}</div>{error&&<p className="text-sm text-destructive">{error}</p>}<p className="text-xs leading-relaxed text-muted-foreground">Longer walls gain windows and an entrance deterministically. Every added floor creates a room slab and another facade row. Angled roofs become less likely as height increases. Exported files can be expanded and imported again.</p></div></aside>
    </div></div>
}

