'use client'

import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { Download, Plus, RotateCcw, Trash2, Upload } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { assetPath } from '@/lib/asset-path'
import { BUILDING_MODULE, BUILDING_TYPES, SEED_FIELDS, normalizeBuildingPreset, normalizeBuildingSeed, parseBuildingPresets, type BuildingPreset, type BuildingType, type FootprintPoint } from '@/lib/game/building-system'
import { BuildingViewport } from './building-viewport'

const randomSeed = () => Array.from({ length: 16 }, () => Math.floor(Math.random() * 10)).join('')
const empty: BuildingPreset = { id: 'custom-building', name: 'Custom building', type: 'residential-house', width: 4, depth: 3, floors: 2, seed: '2417330848621957', roof: 'auto', footprintMode: 'rectangle', slopedWalls: false }
const download = (presets: BuildingPreset[]) => { const url = URL.createObjectURL(new Blob([JSON.stringify(presets, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = '_buildings.json'; link.click(); URL.revokeObjectURL(url) }
const simplify = (points: FootprintPoint[]) => { const result: FootprintPoint[] = []; for (const point of points) { const previous = result[result.length - 1]; if (!previous || Math.hypot(point.x - previous.x, point.y - previous.y) >= .55) result.push(point) } return result.slice(0, 64) }

function FootprintEditor({ value, onChange }: { value: BuildingPreset; onChange: (next: BuildingPreset) => void }) {
  const host = useRef<SVGSVGElement>(null), rectangleStart = useRef<FootprintPoint | null>(null), drawing = useRef<FootprintPoint[]>([])
  const point = (event: PointerEvent<SVGSVGElement>) => { const rect = host.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(16, (event.clientX - rect.left) / rect.width * 16)), y: Math.max(0, Math.min(16, 16 - (event.clientY - rect.top) / rect.height * 16)) } }
  const commitShape = (points: FootprintPoint[]) => { const next = simplify(points); if (next.length < 3) return; const minX = Math.min(...next.map(p => p.x)), maxX = Math.max(...next.map(p => p.x)), minY = Math.min(...next.map(p => p.y)), maxY = Math.max(...next.map(p => p.y)); onChange({ ...value, footprint: next, width: Math.max(1, Math.ceil(maxX - minX)), depth: Math.max(1, Math.ceil(maxY - minY)) }) }
  const move = (event: PointerEvent<SVGSVGElement>) => { const current = point(event); if (value.footprintMode === 'shape') { if (!drawing.current.length) return; drawing.current.push(current); commitShape(drawing.current) } else if (rectangleStart.current) { const start = rectangleStart.current; onChange({ ...value, width: Math.max(1, Math.ceil(Math.abs(current.x - start.x))), depth: Math.max(1, Math.ceil(Math.abs(current.y - start.y))), footprint: undefined }) } }
  const shown = value.footprintMode === 'shape' ? value.footprint || [] : [{ x: 1, y: 1 }, { x: 1 + value.width, y: 1 }, { x: 1 + value.width, y: 1 + value.depth }, { x: 1, y: 1 + value.depth }]
  const points = shown.map(p => `${p.x * 20},${(16 - p.y) * 20}`).join(' ')
  return <svg ref={host} viewBox="0 0 320 320" className="aspect-square w-full touch-none rounded-md border border-border bg-[#101c2a]" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); const start = point(event); if (value.footprintMode === 'shape') { drawing.current = [start]; onChange({ ...value, footprint: [start] }) } else rectangleStart.current = start }} onPointerMove={move} onPointerUp={event => { move(event); rectangleStart.current = null; if (drawing.current.length) commitShape(drawing.current); drawing.current = [] }} aria-label={value.footprintMode === 'shape' ? 'Draw a freeform building outline' : 'Drag to set a rectangular building footprint'}>
    <defs><pattern id="building-grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#32465a" strokeWidth="1" /></pattern></defs><rect width="320" height="320" fill="url(#building-grid)" />
    {points && <polygon points={points} fill="#54b7ff22" stroke="#54b7ff" strokeWidth="2" strokeLinejoin="round" />}
    <text x="10" y="310" fill="#91a6b8" fontSize="12">{value.width * BUILDING_MODULE} × {value.depth * BUILDING_MODULE} m · {value.footprintMode === 'shape' ? 'freeform outline' : 'rectangle'}</text>
  </svg>
}

function SeedEditor({ value, onChange }: { value: string; onChange: (seed: string) => void }) {
  const seed = normalizeBuildingSeed(value), update = (index: number, pair: string) => { const digits = pair.replace(/\D/g, '').slice(0, 2).padStart(2, '0'); onChange(`${seed.slice(0, index * 2)}${digits}${seed.slice(index * 2 + 2)}`) }
  return <div><div className="mb-2 flex items-center justify-between"><span className="text-sm">Structured seed</span><span className="font-mono text-xs text-muted-foreground">{seed.match(/.{2}/g)?.join(' ')}</span></div><div className="grid grid-cols-2 gap-2">{SEED_FIELDS.map((label, index) => <label key={label} className="rounded border border-border p-2 text-[11px] text-muted-foreground">{label}<input className="mt-1 w-full rounded border border-border bg-background px-2 py-1 font-mono text-sm text-foreground" inputMode="numeric" value={seed.slice(index * 2, index * 2 + 2)} onChange={event => update(index, event.target.value)} /></label>)}</div></div>
}

export function BuildingEditor() {
  const [draft, setDraft] = useState<BuildingPreset>(empty), [presets, setPresets] = useState<BuildingPreset[]>([]), [error, setError] = useState('')
  useEffect(() => { let saved: BuildingPreset[] = []; const stored = localStorage.getItem('grid-command-buildings'); if (stored) try { saved = parseBuildingPresets(JSON.parse(stored)) } catch {} fetch(assetPath('/_buildings.json')).then(r => r.json()).then(value => { const defaults = parseBuildingPresets(value), savedIds = new Set(saved.map(item => item.id)), next = [...defaults.filter(item => !savedIds.has(item.id)), ...saved]; setPresets(next); if (next[0]) setDraft(next[0]) }).catch(() => { setPresets(saved); if (saved[0]) setDraft(saved[0]) }) }, [])
  const save = (next: BuildingPreset[]) => { setPresets(next); localStorage.setItem('grid-command-buildings', JSON.stringify(next)) }, select = (preset: BuildingPreset) => { setDraft({ ...preset }); setError('') }, exists = presets.some(p => p.id === draft.id)
  const persist = () => { const preset = normalizeBuildingPreset({ ...draft, id: exists ? draft.id : `${draft.type}-${Date.now()}`, name: draft.name || `${draft.type} building` }); save(exists ? presets.map(item => item.id === preset.id ? preset : item) : [...presets, preset]); select(preset) }
  return <div className="flex h-full min-h-0 w-full flex-col overflow-hidden bg-background"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-6 py-4"><div><h1 className="text-xl font-medium">Building Designer</h1><p className="pt-1 text-sm text-muted-foreground">Draw the footprint and inspect the exact low-poly building used in the battlefield.</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><Upload size={15} />Import JSON<input className="sr-only" type="file" accept="application/json,.json" onChange={async e => { const file=e.target.files?.[0]; if(!file)return; try{const next=parseBuildingPresets(JSON.parse(await file.text()));save(next);select(next[0]||empty);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Invalid building preset file.')}e.target.value='' }} /></label><Button variant="outline" onClick={()=>download(presets)}><Download />Export JSON</Button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-1 overflow-y-auto lg:grid-cols-[290px_minmax(360px,1fr)_350px]"><aside className="border-r border-border p-4"><div className="mb-3 flex items-center justify-between"><span className="eyebrow">PRESETS</span><Button size="icon-sm" variant="ghost" aria-label="New preset" onClick={()=>setDraft({...empty,id:`draft-${Date.now()}`,seed:randomSeed()})}><Plus /></Button></div><div className="flex flex-col gap-2">{presets.map(p=><button key={p.id} onClick={()=>select(p)} className={`rounded-md border px-3 py-3 text-left ${p.id===draft.id?'border-primary bg-primary/10':'border-border hover:bg-secondary'}`}><span className="block text-sm font-medium">{p.name}</span><span className="text-xs text-muted-foreground">{BUILDING_TYPES.find(t=>t.value===p.type)?.label} · {p.width}×{p.depth} · {p.floors}F</span></button>)}</div></aside>
      <main className="relative flex min-h-[560px] items-center justify-center p-5"><BuildingViewport preset={draft} /></main>
      <aside className="border-l border-border p-5"><div className="flex flex-col gap-4"><label className="text-sm">Name<input className="mt-2 w-full rounded-md border border-border bg-background px-3 py-2" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="text-sm">Building type<select className="settings-select mt-2 w-full" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as BuildingType})}>{BUILDING_TYPES.map(type=><option key={type.value} value={type.value}>{type.label}</option>)}</select></label>
        <div><span className="text-sm">Footprint</span><div className="mt-2 grid grid-cols-2 gap-2"><Button size="sm" variant={draft.footprintMode!=='shape'?'default':'outline'} onClick={()=>setDraft({...draft,footprintMode:'rectangle',footprint:undefined})}>Rectangle</Button><Button size="sm" variant={draft.footprintMode==='shape'?'default':'outline'} onClick={()=>setDraft({...draft,footprintMode:'shape',footprint:undefined})}>Draw shape</Button></div><div className="mt-2"><FootprintEditor value={draft} onChange={setDraft}/></div></div>
        <label className="flex items-start justify-between gap-3 rounded-md border border-border p-3 text-sm"><span>Sloped walls<span className="mt-1 block text-xs leading-relaxed text-muted-foreground">Follow diagonal lines in a drawn shape. Off converts them to square corners.</span></span><input type="checkbox" checked={!!draft.slopedWalls} onChange={e=>setDraft({...draft,slopedWalls:e.target.checked})}/></label>
        <label className="text-sm">Floors · {draft.floors}<input className="mt-2 w-full" type="range" min="1" max="40" value={draft.floors} onChange={e=>setDraft({...draft,floors:Number(e.target.value)})}/></label><label className="text-sm">Roof<select className="settings-select mt-2 w-full" value={draft.roof} onChange={e=>setDraft({...draft,roof:e.target.value as BuildingPreset['roof']})}><option value="auto">Deterministic auto</option><option value="flat">Flat</option><option value="gable">Angled</option></select></label>
        <SeedEditor value={draft.seed} onChange={seed=>setDraft({...draft,seed})}/><div className="flex flex-wrap gap-2"><Button onClick={persist}><Plus />{exists?'Save preset':'Add preset'}</Button><Button variant="outline" onClick={()=>setDraft({...draft,seed:randomSeed()})}><RotateCcw />Reroll all</Button>{exists&&<Button variant="destructive" size="icon" aria-label="Delete preset" onClick={()=>{const next=presets.filter(p=>p.id!==draft.id);save(next);select(next[0]||empty)}}><Trash2 /></Button>}</div>{error&&<p className="text-sm text-destructive">{error}</p>}<p className="text-xs leading-relaxed text-muted-foreground">Every building receives at least one entrance. Each seed pair controls one stable visual system, including facade, glazing, roof, entrance placement, spacing and details.</p></div></aside>
    </div></div>
}

