'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import maplibregl from 'maplibre-gl'
import { BattlefieldRenderer } from '@/lib/game/renderer'
import { Visibility } from '@/lib/game/visibility'
import { resolveCombat } from '@/lib/game/combat'
import { initialState, lngLat, prepareUnit, DEFAULT_GRAPHICS, type Role, type GeometryPacket } from '@/lib/game/types'
export function CombatRange(){const host=useRef<HTMLDivElement>(null),[blocked,setBlocked]=useState(true),[role,setRole]=useState<Role>('RIFLE'),[far,setFar]=useState(false),[slow,setSlow]=useState(true),[metrics,setMetrics]=useState('Loading range'),[revision,setRevision]=useState(0)
  useEffect(()=>{if(!host.current)return;const state=initialState();state.units=[state.units[0],state.units.find(u=>u.side==='RED'&&u.role==='RIFLE')!];state.units.forEach((u,i)=>{u.x=i?(far?275:12):(far?-275:-12);u.y=0;u.role=role;u.maxMembers=u.members=1;prepareUnit(u);u.altitude=0;u.heading=i?-Math.PI/2:Math.PI/2;u.soldiers?.forEach(s=>{s.x=u.x;s.y=0;s.heading=u.heading;s.aim=u.heading})});state.geometryReady=true;state.speed=slow?.1:1
    const rings=[[-.2,-5],[.2,-5],[.2,5],[-.2,5],[-.2,-5]].map(([x,y])=>lngLat({x,y})),packet:GeometryPacket={complete:true,version:1,features:blocked?[{key:'test-wall',water:false,roof:4,rings:[rings]}]:[],terrain:{x:-1800,y:-1100,step:50,width:73,height:45,values:Array(73*45).fill(0)}},visibility=new Visibility();visibility.import(packet)
    const map=new maplibregl.Map({container:host.current,style:{version:8,sources:{wall:{type:'geojson',data:{type:'FeatureCollection',features:blocked?[{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[rings]}}]:[]}}},layers:[{id:'background',type:'background',paint:{'background-color':'#172432'}},{id:'wall',type:'fill-extrusion',source:'wall',paint:{'fill-extrusion-color':'#476685','fill-extrusion-height':4,'fill-extrusion-opacity':1}}]},center:lngLat({x:0,y:0}),zoom:far?16.4:20.3,pitch:55,bearing:40,attributionControl:false,pixelRatio:1})
    let renderer:BattlefieldRenderer|null=null,timer:ReturnType<typeof setInterval>|null=null,id=0,frames=0,fps=0
    map.on('load',()=>{renderer=new BattlefieldRenderer(map,null,()=>state,()=>({graphics:{...DEFAULT_GRAPHICS,terrain:false},perspective:'OBS',selected:null}),n=>{fps=n});timer=setInterval(()=>{state.time+=slow?.005:.05;state.tick++;if(state.tick%4===0)resolveCombat(state,visibility,()=>.5,()=>++id);if(++frames%10===0)setMetrics(`${blocked?'WALL BLOCKED':'OPEN SIGHT'} · ${id} shots · BLU ${Math.round(state.units[0].hp)}% / RED ${Math.round(state.units[1].hp)}% · ${fps} FPS`);map.triggerRepaint()},50)})
    return()=>{if(timer)clearInterval(timer);renderer?.dispose();map.remove()}
  },[blocked,role,far,slow,revision])
  return <main className="flex h-dvh flex-col bg-background text-foreground font-sans"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-border p-5"><div><h1 className="text-xl font-semibold">Combat verification range</h1><p className="text-sm text-muted-foreground">Synthetic fixture · production raycaster and shared-depth renderer</p></div><Link href="/" className="text-sm text-primary underline">Return to battlefield</Link></header><div className="flex flex-wrap items-center gap-5 p-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)}/>Building obstruction</label><label className="flex items-center gap-2"><input type="checkbox" checked={far} onChange={e=>setFar(e.target.checked)}/>550 m separation</label><label className="flex items-center gap-2"><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/>0.1× slow motion</label><label className="flex items-center gap-2">Weapon unit<select className="settings-select" value={role} onChange={e=>setRole(e.target.value as Role)}>{['RIFLE','MG','AT','TANK','APC','CANNON_APC','IFV'].map(r=><option key={r}>{r}</option>)}</select></label><button className="map-control" onClick={()=>setRevision(n=>n+1)}>Restart fixture</button></div><p className="px-4 pb-3 text-sm font-mono text-primary" role="status">{metrics}</p><div ref={host} className="min-h-0 flex-1" aria-label="Combat raycast verification map"/></main>
}
