'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import type { BattlefieldAudio } from '@/lib/game/audio'
import { MAX_BANK_BYTES } from '@/lib/game/sfx-schema'
export function SoundSettings({engine}:{engine:BattlefieldAudio}){
  const [,refresh]=useState(0),[error,setError]=useState(''),[preset,setPreset]=useState('RIFLE_FIRE');const update=()=>refresh(n=>n+1)
  return <section className="flex flex-col gap-4 border-t border-border pt-5" aria-label="Sound bank settings"><h3 className="text-base font-medium">Live sound bank</h3><p className="text-sm text-muted-foreground">{engine.filename}</p><div className="settings-row"><label htmlFor="sfx-enabled">Battlefield SFX<p>Separate from radio speech</p></label><input id="sfx-enabled" type="checkbox" checked={engine.enabled} onChange={async e=>{try{await engine.enable(e.target.checked);setError('')}catch{setError('Audio could not start in this browser.')}update()}} /></div><label className="flex flex-col gap-2 text-sm" htmlFor="sfx-volume">Master volume · {Math.round(engine.volume*100)}%<input id="sfx-volume" type="range" min="0" max="1" step=".01" value={engine.volume} onChange={e=>{engine.setVolume(Number(e.target.value));update()}} /></label><label className="flex flex-col gap-2 text-sm" htmlFor="sfx-upload">Upload _sfx.json<input id="sfx-upload" type="file" accept=".json,application/json" className="w-full rounded border border-border p-2 text-sm" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>MAX_BANK_BYTES)throw new Error('Sound bank exceeds 256 KB.');engine.import(await file.text(),file.name);setError('')}catch(err){setError(err instanceof Error?err.message:'Could not read sound bank.')}e.target.value='';update()}} /></label><p role="status" className="text-sm text-muted-foreground">{engine.status}</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex items-center gap-2"><label htmlFor="sfx-preset" className="sr-only">Sound preview preset</label><select id="sfx-preset" value={preset} onChange={e=>setPreset(e.target.value)} className="settings-select min-w-0 flex-1">{Object.entries(engine.bank).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select><Button variant="outline" onClick={async()=>{try{await engine.preview(preset);setError('')}catch{setError('Sound preview unavailable.')}update()}}>Preview sound</Button></div><div className="flex items-center justify-between gap-3"><Button variant="ghost" onClick={()=>{engine.reset();setError('');update()}}>Reset sounds</Button><a href="/grid-command_sfx.json" download className="text-sm text-primary underline">Download example</a></div><p className="text-sm leading-relaxed text-muted-foreground">Validated uploads replace sounds immediately without resetting the battle. Settings stay in this browser. Engine previews stop after two seconds.</p></section>
}
