'use client'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import type { BattlefieldAudio } from '@/lib/game/audio'
import { clonePreset, MAX_BANK_BYTES, type OscillatorPreset, type SoundPreset } from '@/lib/game/sfx-schema'

const waves:OscillatorType[]=['sine','triangle','sawtooth','square']
function Slider({label,value,min,max,step,onChange,suffix=''}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void;suffix?:string}){return <label className="flex flex-col gap-1 text-xs text-muted-foreground"><span className="flex justify-between gap-2"><span>{label}</span><span className="font-mono text-foreground">{Number(value.toFixed(step<1?2:0))}{suffix}</span></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Oscillator({index,value,onChange}:{index:number;value:OscillatorPreset;onChange:(o:OscillatorPreset)=>void}){const set=<K extends keyof OscillatorPreset,>(key:K,next:OscillatorPreset[K])=>onChange({...value,[key]:next});return <div className="rounded-md border border-border bg-muted/20 p-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm">Layer {index+1}</strong><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={value.enabled} onChange={e=>set('enabled',e.target.checked)}/>On</label></div><label className="mt-3 flex items-center justify-between gap-2 text-xs text-muted-foreground">Waveform<select className="settings-select" value={value.wave} onChange={e=>set('wave',e.target.value as OscillatorType)}>{waves.map(w=><option key={w} value={w}>{w[0].toUpperCase()+w.slice(1)}</option>)}</select></label><div className="grid grid-cols-2 gap-3 pt-3"><Slider label="Base pitch" value={value.freq} min={20} max={4000} step={1} suffix=" Hz" onChange={n=>set('freq',n)}/><Slider label="Coarse" value={value.ratio} min={.01} max={20} step={.01} suffix="×" onChange={n=>set('ratio',n)}/><Slider label="Fine" value={value.detune} min={-1200} max={1200} step={1} suffix=" ct" onChange={n=>set('detune',n)}/><Slider label="Level" value={value.gain} min={0} max={2} step={.01} onChange={n=>set('gain',n)}/><Slider label="Pan" value={value.pan} min={-1} max={1} step={.01} onChange={n=>set('pan',n)}/><Slider label="Phase" value={value.phase} min={0} max={360} step={1} suffix="°" onChange={n=>set('phase',n)}/><Slider label="Pitch sweep" value={value.endRatio} min={.05} max={4} step={.01} suffix="×" onChange={n=>set('endRatio',n)}/></div></div>}

export function SoundSettings({engine}:{engine:BattlefieldAudio}){
  const keys=Object.keys(engine.bank),[preset,setPreset]=useState(keys.includes('RIFLE_FIRE')?'RIFLE_FIRE':keys[0]),[draft,setDraft]=useState(()=>clonePreset(engine.bank[keys.includes('RIFLE_FIRE')?'RIFLE_FIRE':keys[0]])),[error,setError]=useState(''),[,refresh]=useState(0)
  useEffect(()=>engine.subscribe(()=>{setPreset(current=>{const next=engine.bank[current]?current:Object.keys(engine.bank)[0];setDraft(clonePreset(engine.bank[next]));return next});refresh(n=>n+1)}),[engine])
  const redraw=()=>refresh(n=>n+1),commit=(next:SoundPreset)=>{setDraft(next);engine.updatePreset(preset,next);redraw()},field=<K extends keyof SoundPreset,>(key:K,value:SoundPreset[K])=>commit({...draft,[key]:value}),select=(key:string)=>{engine.stopPreviews();setPreset(key);setDraft(clonePreset(engine.bank[key]));setError('')}
  const download=()=>{const blob=new Blob([engine.exportBank()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='_sfx.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  return <section className="flex flex-col gap-4 border-t border-border pt-5" aria-label="Sound effects editor"><div><h3 className="text-base font-medium">Sound designer</h3><p className="pt-1 text-sm text-muted-foreground">Shape each battlefield sound with three simple tone layers.</p></div><div className="settings-row"><label htmlFor="sfx-enabled">Battlefield SFX<p>Separate from radio speech</p></label><input id="sfx-enabled" type="checkbox" checked={engine.enabled} onChange={async e=>{try{await engine.enable(e.target.checked);setError('')}catch{setError('Audio could not start in this browser.')}redraw()}}/></div><Slider label="Master volume" value={engine.volume} min={0} max={1} step={.01} onChange={n=>{engine.setVolume(n);redraw()}}/><label className="flex flex-col gap-2 text-sm">Sound event<select className="settings-select" value={preset} onChange={e=>select(e.target.value)}>{keys.map(id=><option key={id} value={id}>{engine.bank[id].name}</option>)}</select></label><div className="flex flex-wrap gap-2"><Button onClick={async()=>{try{engine.updatePreset(preset,draft);await engine.preview(preset);setError('')}catch{setError('Sound preview unavailable.')}redraw()}}>Preview</Button><Button variant="outline" onClick={()=>{engine.stopPreviews();redraw()}}>Stop</Button><Button variant="ghost" onClick={()=>{engine.resetPreset(preset);setDraft(clonePreset(engine.bank[preset]));setError('');redraw()}}>Reset this sound</Button></div>
  <div className="flex flex-col gap-3">{draft.oscillators.slice(0,3).map((osc,index)=><Oscillator key={index} index={index} value={osc} onChange={next=>commit({...draft,oscillators:draft.oscillators.map((o,i)=>i===index?next:o)})}/>)}</div>
  <details open className="rounded-md border border-border p-3"><summary className="cursor-pointer text-sm font-medium">Shape and tone</summary><div className="grid grid-cols-2 gap-3 pt-4"><Slider label="Attack" value={draft.attack} min={0} max={3} step={.01} suffix=" s" onChange={n=>field('attack',n)}/><Slider label="Decay" value={draft.decay} min={0} max={5} step={.01} suffix=" s" onChange={n=>field('decay',n)}/><Slider label="Sustain" value={draft.sustain} min={0} max={1} step={.01} onChange={n=>field('sustain',n)}/><Slider label="Release" value={draft.release} min={0} max={5} step={.01} suffix=" s" onChange={n=>field('release',n)}/><Slider label="Length" value={draft.duration} min={.01} max={10} step={.01} suffix=" s" onChange={n=>field('duration',n)}/><Slider label="Output" value={draft.output} min={0} max={2} step={.01} onChange={n=>field('output',n)}/><label className="flex flex-col gap-1 text-xs text-muted-foreground">Filter<select className="settings-select" value={draft.filterType} onChange={e=>field('filterType',e.target.value as BiquadFilterType)}>{['lowpass','highpass','bandpass','notch','allpass','peaking','lowshelf','highshelf'].map(v=><option key={v}>{v}</option>)}</select></label><Slider label="Filter cutoff" value={draft.filterFreq} min={20} max={20000} step={10} suffix=" Hz" onChange={n=>field('filterFreq',n)}/><Slider label="Filter focus" value={draft.filterQ} min={0} max={30} step={.1} onChange={n=>field('filterQ',n)}/><Slider label="Noise" value={draft.noiseGain} min={0} max={2} step={.01} onChange={n=>field('noiseGain',n)}/><Slider label="Noise tone" value={draft.noiseFreq} min={20} max={20000} step={10} suffix=" Hz" onChange={n=>field('noiseFreq',n)}/><Slider label="Drive" value={draft.distortion} min={0} max={50} step={.1} onChange={n=>field('distortion',n)}/></div></details>
  {draft.vehicle&&<details className="rounded-md border border-border p-3"><summary className="cursor-pointer text-sm font-medium">Movement response</summary><div className="grid grid-cols-2 gap-3 pt-4"><Slider label="Pitch at speed" value={draft.speedPitchMax} min={.25} max={4} step={.01} suffix="×" onChange={n=>field('speedPitchMax',n)}/><Slider label="Filter at speed" value={draft.speedFilterMax} min={.25} max={4} step={.01} suffix="×" onChange={n=>field('speedFilterMax',n)}/><Slider label="Pulse rate" value={draft.repeatHz} min={0} max={40} step={.1} suffix=" Hz" onChange={n=>field('repeatHz',n)}/><Slider label="Pulse speed" value={draft.repeatSpeedMax} min={.05} max={8} step={.01} suffix="×" onChange={n=>field('repeatSpeedMax',n)}/><Slider label="Pulse depth" value={draft.repeatDepth} min={0} max={1} step={.01} onChange={n=>field('repeatDepth',n)}/></div></details>}
  <label className="flex flex-col gap-2 text-sm">Import sound bank<input type="file" accept=".json,application/json" className="w-full rounded border border-border p-2 text-sm" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>MAX_BANK_BYTES)throw new Error('Sound bank exceeds 256 KB.');engine.import(await file.text(),file.name);await engine.enable(true);const next=Object.keys(engine.bank).includes(preset)?preset:Object.keys(engine.bank)[0];select(next);setError('')}catch(err){setError(err instanceof Error?err.message:'Could not read sound bank.')}e.target.value='';redraw()}}/></label><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={download}>Download bank</Button><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(engine.exportBank());engine.status='Sound bank copied';setError('')}catch{setError('Clipboard access was blocked.')}redraw()}}>Copy bank</Button><Button variant="ghost" onClick={()=>{engine.reset();select(Object.keys(engine.bank)[0]);redraw()}}>Reset all</Button></div><p role="status" className="text-sm text-muted-foreground">{engine.status}</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<p className="text-xs leading-relaxed text-muted-foreground">Edits apply immediately and stay in this browser. Imported missing or invalid controls fall back to the supplied bank.</p></section>
}
