'use client'
import { useEffect, useId, useRef, useState } from 'react'
import type { BattlefieldAudio } from '@/lib/game/audio'
import { clonePreset, MAX_BANK_BYTES, type OscillatorPreset, type SoundPreset } from '@/lib/game/sfx-schema'
import styles from './sound-settings.module.css'

const waves:OscillatorType[]=['sine','square','triangle','sawtooth']
const filters:BiquadFilterType[]=['lowpass','highpass','bandpass','notch','allpass','peaking','lowshelf','highshelf']
function WaveIcon({wave}:{wave:OscillatorType}){const d=wave==='sine'?'M1 8c3-8 7 8 10 0s7 8 10 0':wave==='square'?'M1 11V5h7v6h7V5h7':wave==='triangle'?'M1 11 7 5l7 6 7-6':'M1 11 8 5v6l7-6v6l7-6';return <svg viewBox="0 0 23 16" aria-hidden="true"><path d={d}/></svg>}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(n:boolean)=>void;label:string}){return <label className={styles.toggle}><span className="sr-only">{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span aria-hidden="true"/></label>}
type CP={label:string;value:number;min:number;max:number;step:number;suffix?:string;onChange:(n:number)=>void;disabled?:boolean}
const dp=(s:number)=>s<.1?2:s<1?1:0
function Fader({label,value,min,max,step,suffix='',onChange,disabled}:CP){const id=useId();return <label className={styles.fader} htmlFor={id}><span className={styles.controlLabel}>{label}</span><span className={styles.faderTrack}><input id={id} type="range" min={min} max={max} step={step} value={value} disabled={disabled} onChange={e=>onChange(+e.target.value)}/></span><output htmlFor={id}>{+value.toFixed(dp(step))}{suffix}</output></label>}
function Rotary({label,value,min,max,step,suffix='',onChange,disabled}:CP){const id=useId(),a=-135+Math.max(0,Math.min(1,(value-min)/(max-min)))*270;return <label className={styles.rotary} htmlFor={id}><span className={styles.knob} style={{'--knob-angle':`${a}deg`} as React.CSSProperties} aria-hidden="true"><i/></span><span className={styles.controlLabel}>{label}</span><output htmlFor={id}>{+value.toFixed(dp(step))}{suffix}</output><input id={id} type="range" min={min} max={max} step={step} value={value} disabled={disabled} onChange={e=>onChange(+e.target.value)}/></label>}
function Compact({label,value,min,max,step,suffix='',onChange}:CP){const id=useId();return <label className={styles.compact} htmlFor={id}><span>{label}</span><output htmlFor={id}>{+value.toFixed(dp(step))}{suffix}</output><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function Oscillator({index,value,onChange}:{index:number;value:OscillatorPreset;onChange:(o:OscillatorPreset)=>void}){const set=<K extends keyof OscillatorPreset>(k:K,n:OscillatorPreset[K])=>onChange({...value,[k]:n});return <section className={`${styles.oscillator} ${value.enabled?'':styles.disabled}`} aria-label={`Oscillator layer ${index+1}`}><div className={styles.layerSwitch}><strong>{index+1}</strong><Toggle checked={value.enabled} onChange={n=>set('enabled',n)} label={`Enable oscillator layer ${index+1}`}/></div><fieldset className={styles.waveforms} disabled={!value.enabled}><legend>Waveform</legend><div>{waves.map(w=><button key={w} type="button" className={value.wave===w?styles.selectedWave:''} aria-label={`${w} waveform`} aria-pressed={value.wave===w} onClick={()=>set('wave',w)}><WaveIcon wave={w}/></button>)}</div></fieldset><div className={styles.faders}><Fader label="Phase" value={value.phase} min={0} max={360} step={1} suffix="°" disabled={!value.enabled} onChange={n=>set('phase',n)}/><Fader label="Detune" value={value.detune} min={-1200} max={1200} step={1} suffix=" ct" disabled={!value.enabled} onChange={n=>set('detune',n)}/></div><div className={styles.rotaries}><Rotary label="Coarse" value={value.freq} min={20} max={4000} step={1} suffix=" Hz" disabled={!value.enabled} onChange={n=>set('freq',n)}/><Rotary label="Fine" value={value.ratio} min={.01} max={20} step={.01} suffix="×" disabled={!value.enabled} onChange={n=>set('ratio',n)}/><Rotary label="Level" value={value.gain} min={0} max={2} step={.01} disabled={!value.enabled} onChange={n=>set('gain',n)}/><Rotary label="Sweep" value={value.endRatio} min={.05} max={4} step={.01} suffix="×" disabled={!value.enabled} onChange={n=>set('endRatio',n)}/><Rotary label="Pan" value={value.pan} min={-1} max={1} step={.01} disabled={!value.enabled} onChange={n=>set('pan',n)}/></div></section>}

export function SoundSettings({engine}:{engine:BattlefieldAudio}){
 const keys=Object.keys(engine.bank),first=keys.includes('RIFLE_FIRE')?'RIFLE_FIRE':keys[0],[preset,setPreset]=useState(first),[draft,setDraft]=useState(()=>clonePreset(engine.bank[first])),[error,setError]=useState(''),[,refresh]=useState(0),importRef=useRef<HTMLInputElement>(null)
 useEffect(()=>engine.subscribe(()=>{setPreset(current=>{const next=engine.bank[current]?current:Object.keys(engine.bank)[0];setDraft(clonePreset(engine.bank[next]));return next});refresh(n=>n+1)}),[engine])
 const redraw=()=>refresh(n=>n+1),commit=(next:SoundPreset)=>{setDraft(next);engine.updatePreset(preset,next);redraw()},field=<K extends keyof SoundPreset>(key:K,value:SoundPreset[K])=>commit({...draft,[key]:value}),select=(key:string)=>{engine.stopPreviews();setPreset(key);setDraft(clonePreset(engine.bank[key]));setError('')}
 const download=()=>{const blob=new Blob([engine.exportBank()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='_sfx.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
 const audition=async()=>{try{engine.updatePreset(preset,draft);await engine.preview(preset,draft);setError('')}catch{setError('Sound preview unavailable.')}redraw()}
 const kind=(id:string,s:SoundPreset)=>s.vehicle?'VEHICLE':/FIRE|CANNON|ROCKET|IMPACT/.test(id)?'WEAPON':/RADIO|OBJECTIVE|CAPTURE/.test(id)?'UI':'EFFECT'
 return <section className={styles.workspace} aria-label="Sound effects editor"><aside className={styles.library}><header><span>Sound events</span><span>{keys.length} sounds</span></header><nav aria-label="Sound event presets">{keys.map(id=>{const s=engine.bank[id];return <button key={id} type="button" className={id===preset?styles.activeEvent:''} aria-current={id===preset?'true':undefined} onClick={()=>select(id)}><strong>{s.name}</strong><small>{kind(id,s)} · {s.oscillators.length} LAYERS</small></button>})}</nav><footer><Compact label="Master volume" value={engine.volume} min={0} max={1} step={.01} onChange={n=>{engine.setVolume(n);redraw()}}/><div className={styles.libraryActions}><button type="button" onClick={()=>importRef.current?.click()}>Import</button><button type="button" onClick={download}>Export</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(engine.exportBank());engine.status='Sound bank copied';setError('')}catch{setError('Clipboard access was blocked.')}redraw()}}>Copy</button><button type="button" onClick={()=>{engine.reset();select(Object.keys(engine.bank)[0]);redraw()}}>Reset all</button><input ref={importRef} type="file" accept=".json,application/json" className="sr-only" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>MAX_BANK_BYTES)throw new Error('Sound bank exceeds 256 KB.');engine.import(await file.text(),file.name);await engine.enable(true);select(Object.keys(engine.bank).includes(preset)?preset:Object.keys(engine.bank)[0]);setError('')}catch(err){setError(err instanceof Error?err.message:'Could not read sound bank.')}e.target.value='';redraw()}}/></div></footer></aside>
 <div className={styles.instrument}><header className={styles.instrumentHeader}><div><span>{draft.oscillators.length}-layer tone generator</span><h2>{draft.name}</h2></div><div className={styles.transport}><label><Toggle checked={engine.enabled} onChange={async n=>{try{await engine.enable(n);setError('')}catch{setError('Audio could not start in this browser.')}redraw()}} label="Enable battlefield sound effects"/><span>SFX</span></label><button className={styles.primaryAction} type="button" onClick={audition}>Audition</button><button type="button" onClick={()=>{engine.stopPreviews();redraw()}}>Stop</button><button type="button" onClick={()=>{engine.resetPreset(preset);setDraft(clonePreset(engine.bank[preset]));setError('');redraw()}}>Reset</button></div></header>
 <div className={styles.oscillatorStack}>{draft.oscillators.slice(0,3).map((osc,index)=><Oscillator key={index} index={index} value={osc} onChange={next=>commit({...draft,oscillators:draft.oscillators.map((o,i)=>i===index?next:o)})}/>)}</div>
 <section className={styles.globalControls} aria-label="Global sound controls"><div className={styles.globalTitle}><span>Global</span><label>Filter<select value={draft.filterType} onChange={e=>field('filterType',e.target.value as BiquadFilterType)}>{filters.map(f=><option key={f}>{f}</option>)}</select></label><label><input type="checkbox" checked={draft.loop} onChange={e=>field('loop',e.target.checked)}/> Loop</label></div><div className={styles.globalGrid}><Compact label="Attack" value={draft.attack} min={0} max={3} step={.01} suffix=" s" onChange={n=>field('attack',n)}/><Compact label="Decay" value={draft.decay} min={0} max={5} step={.01} suffix=" s" onChange={n=>field('decay',n)}/><Compact label="Sustain" value={draft.sustain} min={0} max={1} step={.01} onChange={n=>field('sustain',n)}/><Compact label="Release" value={draft.release} min={0} max={5} step={.01} suffix=" s" onChange={n=>field('release',n)}/><Compact label="Length" value={draft.duration} min={.01} max={10} step={.01} suffix=" s" onChange={n=>field('duration',n)}/><Compact label="Output" value={draft.output} min={0} max={2} step={.01} onChange={n=>field('output',n)}/><Compact label="Cutoff" value={draft.filterFreq} min={20} max={20000} step={10} suffix=" Hz" onChange={n=>field('filterFreq',n)}/><Compact label="Focus" value={draft.filterQ} min={0} max={30} step={.1} onChange={n=>field('filterQ',n)}/><Compact label="Noise" value={draft.noiseGain} min={0} max={2} step={.01} onChange={n=>field('noiseGain',n)}/><Compact label="Noise tone" value={draft.noiseFreq} min={20} max={20000} step={10} suffix=" Hz" onChange={n=>field('noiseFreq',n)}/><Compact label="Drive" value={draft.distortion} min={0} max={50} step={.1} onChange={n=>field('distortion',n)}/>{draft.vehicle&&<><Compact label="Speed pitch" value={draft.speedPitchMax} min={.25} max={4} step={.01} suffix="×" onChange={n=>field('speedPitchMax',n)}/><Compact label="Speed filter" value={draft.speedFilterMax} min={.25} max={4} step={.01} suffix="×" onChange={n=>field('speedFilterMax',n)}/><Compact label="Pulse rate" value={draft.repeatHz} min={0} max={40} step={.1} suffix=" Hz" onChange={n=>field('repeatHz',n)}/><Compact label="Pulse speed" value={draft.repeatSpeedMax} min={.05} max={8} step={.01} suffix="×" onChange={n=>field('repeatSpeedMax',n)}/><Compact label="Pulse depth" value={draft.repeatDepth} min={0} max={1} step={.01} onChange={n=>field('repeatDepth',n)}/></>}</div></section><div className={styles.status} aria-live="polite"><span>{error||engine.status||'Edits apply immediately and stay in this browser.'}</span><span>{draft.oscillators.filter(o=>!o.enabled).length?`${draft.oscillators.filter(o=>!o.enabled).length} layer muted`:'All layers active'}</span></div></div></section>
}
