import { DEFAULT_BANK, parseSoundBank, type SoundBank, type SoundPreset } from './sfx-schema'
import { isVehicle, type BattleState, type Perspective, type Point } from './types'
interface Voice {stop:()=>void;update:(speed:number,gain:number,pan:number)=>void}
export class BattlefieldAudio {
  bank:SoundBank=DEFAULT_BANK;filename='grid-command_sfx.json';enabled=false;volume=.4;context:AudioContext|null=null;master:GainNode|null=null;voices=new Set<Voice>();previews=new Set<Voice>();loops=new Map<string,Voice>();lastEvent=0;lastTime=0;lastRadio=0;lastStep=0;status='Original 18-preset sound bank';noise:AudioBuffer|null=null;pending:{time:number;x:number;y:number}[]=[]
  restore(){try{const saved=localStorage.getItem('grid-command-sfx');if(saved){const d=JSON.parse(saved);this.bank=parseSoundBank(JSON.stringify(d.bank)).bank;this.filename=typeof d.filename==='string'?d.filename.slice(0,120):'Saved bank';this.volume=typeof d.volume==='number'?Math.max(0,Math.min(1,d.volume)):.4;this.status='Restored local sound bank · enable SFX to listen'}}catch{this.status='Local settings unavailable; using supplied defaults'}}
  save(){try{localStorage.setItem('grid-command-sfx',JSON.stringify({bank:this.bank,filename:this.filename,volume:this.volume}))}catch{this.status+=' · local storage unavailable'}}
  import(text:string,name:string){if(!/_sfx\.json$/i.test(name))throw new Error('Choose a filename ending in _sfx.json.');const result=parseSoundBank(text,this.bank);this.stop();this.bank=result.bank;this.filename=name;this.status=`Loaded ${result.replaced} presets · ${result.retained} retained`;this.save();return this.status}
  reset(){this.stop();this.bank=DEFAULT_BANK;this.filename='grid-command_sfx.json';this.status='Restored supplied sound bank';this.save()}
  async enable(value:boolean){if(!value){this.enabled=false;this.stop();return}if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=8;limiter.ratio.value=12;limiter.attack.value=.003;limiter.release.value=.15;this.master.connect(limiter);limiter.connect(this.context.destination);this.noise=this.context.createBuffer(1,this.context.sampleRate*2,this.context.sampleRate);const a=this.noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1}await this.context.resume();this.enabled=true;this.master!.gain.value=this.volume}
  setVolume(value:number){this.volume=Math.max(0,Math.min(1,value));if(this.master&&this.context)this.master.gain.setTargetAtTime(this.volume,this.context.currentTime,.03);this.save()}
  stop(includePreviews=true){for(const voice of this.voices)if(includePreviews||!this.previews.has(voice))voice.stop();this.loops.clear();this.pending=[]}
  async preview(key:string){await this.enable(true);const voice=this.play(key,.5,0,0);if(voice)this.previews.add(voice);if(this.bank[key]?.loop)setTimeout(()=>voice?.stop(),2000)}
  play(key:string,gain=1,pan=0,speed=0):Voice|null {
    const ctx=this.context,p=this.bank[key];if(!ctx||!this.master||!this.enabled||!p||this.voices.size>=32)return null;const now=ctx.currentTime,nodes:AudioNode[]=[],sources:AudioScheduledSourceNode[]=[],oscillators:OscillatorNode[]=[]
    const bus=ctx.createGain(),filter=ctx.createBiquadFilter(),distortion=ctx.createWaveShaper(),envelope=ctx.createGain(),spatial=ctx.createGain(),stereo=ctx.createStereoPanner();nodes.push(bus,filter,distortion,envelope,spatial,stereo)
    filter.type=p.filterType;filter.Q.value=p.filterQ;const curve=new Float32Array(512);for(let i=0;i<512;i++){const x=i/255.5-1;curve[i]=(1+p.distortion)*x/(1+p.distortion*Math.abs(x))}distortion.curve=curve
    bus.connect(filter);filter.connect(distortion);distortion.connect(envelope);envelope.connect(spatial);spatial.connect(stereo);stereo.connect(this.master)
    const sustain=Math.max(p.duration,p.attack+p.decay),end=now+sustain+p.release;envelope.gain.setValueAtTime(0,now);envelope.gain.linearRampToValueAtTime(p.output,now+Math.max(.001,p.attack));envelope.gain.linearRampToValueAtTime(p.output*p.sustain,now+Math.max(.002,p.attack+p.decay));if(!p.loop){envelope.gain.setValueAtTime(p.output*p.sustain,now+sustain);envelope.gain.linearRampToValueAtTime(0,end)}
    for(const o of p.oscillators){if(!o.enabled)continue;const osc=ctx.createOscillator(),g=ctx.createGain();osc.type=o.wave;osc.detune.value=o.detune;g.gain.value=o.gain;osc.connect(g);g.connect(bus);sources.push(osc);nodes.push(osc,g);oscillators.push(osc)}
    if(p.noiseGain>0){const noise=ctx.createBufferSource(),nf=ctx.createBiquadFilter(),ng=ctx.createGain();noise.buffer=this.noise;noise.loop=true;nf.type='lowpass';nf.frequency.value=p.noiseFreq;ng.gain.value=p.noiseGain;noise.connect(nf);nf.connect(ng);ng.connect(bus);sources.push(noise);nodes.push(noise,nf,ng)}
    let repeat:OscillatorNode|undefined;if(p.repeatHz>0){repeat=ctx.createOscillator();const depth=ctx.createGain();depth.gain.value=p.repeatDepth*.5;bus.gain.value=1-p.repeatDepth*.5;repeat.connect(depth);depth.connect(bus.gain);sources.push(repeat);nodes.push(repeat,depth)}
    let stopped=false;const cleanup=()=>{nodes.forEach(n=>n.disconnect());this.voices.delete(voice);this.previews.delete(voice)}
    const voice:Voice={stop:()=>{if(stopped)return;stopped=true;envelope.gain.cancelScheduledValues(ctx.currentTime);envelope.gain.setTargetAtTime(0,ctx.currentTime,.015);for(const s of sources){try{s.stop(ctx.currentTime+.06)}catch{}}setTimeout(cleanup,90)},update:(velocity,level,balance)=>{const t=ctx.currentTime,v=Math.max(0,Math.min(1,velocity));spatial.gain.setTargetAtTime(level,t,.04);stereo.pan.setTargetAtTime(Math.max(-1,Math.min(1,balance)),t,.04);filter.frequency.setTargetAtTime(Math.min(ctx.sampleRate*.45,p.filterFreq*(1+(p.speedFilterMax-1)*v)),t,.04);let j=0;for(const o of p.oscillators){if(!o.enabled)continue;const osc=oscillators[j++],hz=Math.max(1,Math.min(20000,o.freq*o.ratio*(1+(p.speedPitchMax-1)*v)));if(p.loop)osc.frequency.setTargetAtTime(hz,t,.05);else{osc.frequency.setValueAtTime(hz,now);osc.frequency.exponentialRampToValueAtTime(Math.max(1,hz*o.endRatio),now+p.duration)}}if(repeat)repeat.frequency.setTargetAtTime(p.repeatHz*(1+(p.repeatSpeedMax-1)*v),t,.04)}}
    voice.update(speed,gain,pan);this.voices.add(voice);for(const s of sources){s.start(now);if(!p.loop)s.stop(end+.01)}if(!p.loop)setTimeout(cleanup,(end-now)*1000+100);return voice
  }
  update(state:BattleState,perspective:Perspective,listener:Point){const newest=state.shots.at(-1)?.id||0;if(state.time<this.lastTime){this.stop();this.lastEvent=0;this.lastRadio=0}this.lastTime=state.time
    if(!this.enabled||state.paused||state.winner||document.hidden){this.stop(!this.enabled||document.hidden);this.lastEvent=newest;this.lastRadio=state.events[0]?.id||0;return}
    const level=(p:Point)=>1/(1+Math.hypot(p.x-listener.x,p.y-listener.y)/100),pan=(p:Point)=>(p.x-listener.x)/500
    for(const e of state.shots){if(e.id<=this.lastEvent||state.time-e.time>.5||(perspective!=='OBS'&&e.side!==perspective&&!e.spotted))continue;this.play(e.sound,level(e.start),pan(e.start));if(e.blast)this.pending.push({time:e.time+Math.hypot(e.end.x-e.start.x,e.end.y-e.start.y,e.end.z-e.start.z)/e.speed,x:e.end.x,y:e.end.y})}this.lastEvent=newest
    this.pending=this.pending.filter(p=>{if(p.time>state.time)return true;if(state.time-p.time<.5)this.play('EXPLOSION',level(p),pan(p));return false}).slice(-64)
    const units=state.units.filter(u=>u.hp>0&&u.engine&&u.fuel>0&&u.role!=='UAV_JAMMER'&&u.transport?.phase!=='departed'&&isVehicle(u.role)&&(perspective==='OBS'||u.side===perspective||u.spotted)).sort((a,b)=>level(b)-level(a)).slice(0,5),ids=new Set(units.map(u=>u.id));for(const[id,voice]of this.loops)if(!ids.has(id)){voice.stop();this.loops.delete(id)}
    for(const u of units){const key=u.role==='CARGO_PLANE'?'CARGO_JET_ENGINE':u.role==='HEAVY_LIFT_HELI'?'HEAVYLIFT_HELO_ENGINE':u.role==='TRANSPORT_HELI'?'TRANSPORT_HELO_ENGINE':u.role==='JET'?'CAS_JET_ENGINE':u.role==='ATTACK_HELI'?'ATTACK_HELO_ENGINE':u.role==='TANK'?'TANK_ENGINE':'VEHICLE_ENGINE';let voice=this.loops.get(u.id);const velocity=u.path.length?1:.15;if(!voice){voice=this.play(key,level(u)*.25,pan(u),velocity)||undefined;if(voice)this.loops.set(u.id,voice)}voice?.update(velocity,level(u)*.25,pan(u))}
    const event=state.events[0];if(event&&event.id>this.lastRadio&&(perspective==='OBS'||event.side===perspective||event.side==='SYS'))this.play('RADIO_SQUELCH',.15);this.lastRadio=event?.id||0
    if(state.time-this.lastStep>.4){this.lastStep=state.time;const u=state.units.find(u=>u.hp>0&&!u.carrier&&u.soldiers?.some(s=>s.status==='active'&&s.action==='walk')&&Math.hypot(u.x-listener.x,u.y-listener.y)<80&&(perspective==='OBS'||u.side===perspective||u.spotted));if(u)this.play('FOOTSTEP',level(u)*.2,pan(u))}
  }
  dispose(){this.stop();void this.context?.close();this.context=null}
}
