import * as T from 'three'
import { MercatorCoordinate, type Map as GeographicMap, type CustomLayerInterface } from 'maplibre-gl'
import { BASES, AIRBASES, CENTER, CATALOG, SIDE_COLOR, isAir, isVehicle, lngLat, type BattleState, type Graphics, type Perspective, type Role, type Side } from './types'
import { SoldierBatch, vehicleGeometry } from './unit-models'
import { createAircraft, animateAircraft, disposeModel } from './aircraft-models'
import { createSupportModel, isSupportModel, animateSupport } from './support-models'
import type { Unit } from './types'
import { createBase, conformBase } from './base-models'

export class BattlefieldRenderer {
  corpseBatches: Record<Side,SoldierBatch[]> = {BLU:[],RED:[]};
  aircraft=new Map<string,T.Group>();bases:{model:T.Group;point:{x:number;y:number;id:string}}[]=[]
  renderer!:T.WebGLRenderer;scene=new T.Scene();camera=new T.Camera();transform=new T.Matrix4();dummy=new T.Object3D();groups=new Map<string,T.InstancedMesh>();soldiers:Record<Side,SoldierBatch>;effects=new Map<string,T.InstancedMesh>();layer:CustomLayerInterface;disposed=false;previous=0;report=0;frames:number[]=[];ground=new Map<string,{x:number;y:number;z:number;time:number}>();snapshotTime=-1;arrival=0
  constructor(public map:GeographicMap,_canvas:HTMLCanvasElement|null,public getState:()=>BattleState,public getSettings:()=>{graphics:Graphics;perspective:Perspective;selected:string|null;active?:boolean},public onFPS:(n:number)=>void){
    const material=new T.MeshStandardMaterial({vertexColors:true,roughness:.85,metalness:.08,flatShading:true});this.soldiers={BLU:new SoldierBatch(this.scene,'BLU',material),RED:new SoldierBatch(this.scene,'RED',material)}
    const sky=new T.HemisphereLight('#dbe7ef','#172432',2.3);sky.position.set(0,0,1);this.scene.add(sky);const sun=new T.DirectionalLight('#dbe7ef',3);sun.position.set(-400,200,600);this.scene.add(sun)
    for(const side of ['BLU','RED'] as Side[])for(const role of Object.keys(CATALOG) as Role[]){if(!isVehicle(role)||isAir(role))continue;const mesh=new T.InstancedMesh(vehicleGeometry(role,side),material,64);mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.groups.set(`${side}-${role}`,mesh);this.scene.add(mesh);if(['TANK','APC','IFV','CANNON_APC','ATTACK_HELI'].includes(role)){const turret=new T.InstancedMesh(vehicleGeometry(role,side,true),material,64);turret.count=0;turret.frustumCulled=false;this.groups.set(`${side}-${role}-attachment`,turret);this.scene.add(turret)}}
    for(const side of ['BLU','RED'] as Side[])for(const kind of ['MOB','AIRFIELD'] as const){const model=createBase(kind,side),point={...(kind==='MOB'?BASES[side]:AIRBASES[side]),id:`${side}-${kind}`};model.position.set(point.x,point.y,0);this.scene.add(model);this.bases.push({model,point})}
    for(const side of ['BLU','RED'] as Side[])for(const type of ['core','glow','blast']){const mesh=new T.InstancedMesh(new T.IcosahedronGeometry(1,type==='blast'?1:0),new T.MeshBasicMaterial({color:SIDE_COLOR[side],transparent:type!=='core',opacity:type==='core'?1:type==='blast'?.32:.2,blending:type==='core'?T.NormalBlending:T.AdditiveBlending,depthWrite:type==='core',depthTest:true}),512);mesh.count=0;mesh.frustumCulled=false;this.effects.set(`${side}-${type}`,mesh);this.scene.add(mesh)}
    const smoke=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),new T.MeshStandardMaterial({color:'#89959a',transparent:true,opacity:.55,roughness:1,depthWrite:false,flatShading:true}),192);smoke.count=0;smoke.frustumCulled=false;this.effects.set('smoke',smoke);this.scene.add(smoke)
    const shadow=new T.InstancedMesh(new T.CircleGeometry(1,12),new T.MeshBasicMaterial({color:'#0b1119',transparent:true,opacity:.3,depthWrite:false}),256);shadow.count=0;shadow.frustumCulled=false;this.effects.set('shadow',shadow);this.scene.add(shadow)
    const origin=MercatorCoordinate.fromLngLat(CENTER,0),s=origin.meterInMercatorCoordinateUnits();this.transform.makeTranslation(origin.x,origin.y,0).scale(new T.Vector3(s,-s,s))
    this.layer={id:'battlefield-projection',type:'custom',renderingMode:'3d',onAdd:(_map,gl)=>{this.renderer=new T.WebGLRenderer({canvas:map.getCanvas(),context:gl as WebGL2RenderingContext,antialias:false});this.renderer.autoClear=false;this.renderer.outputColorSpace=T.SRGBColorSpace},render:(_gl,matrix)=>this.render(matrix as number[])};map.addLayer(this.layer)
    if(process.env.NODE_ENV==='development') (window as unknown as {gridDebug:BattlefieldRenderer}).gridDebug=this
  }
  resize(){this.map.triggerRepaint()}
  altitude(p:{x:number;y:number;id:string},now:number){if(!this.map.getTerrain())return 0;for(const {model,point}of this.bases){const x=p.x-point.x,y=p.y-point.y,inside=model.name==='MOB'?Math.abs(x)<41&&Math.abs(y)<35:(Math.abs(x+48)<17&&Math.abs(y)<600)||(model.userData.tier===3&&Math.abs(x+118)<17&&Math.abs(y)<600)||(Math.abs(x)<85&&Math.abs(y)<210);if(inside&&Number.isFinite(model.userData.platformHeight))return model.userData.platformHeight+1.3}const old=this.ground.get(p.id);if(old&&now-old.time<600&&Math.hypot(old.x-p.x,old.y-p.y)<5)return old.z;const z=(this.map.queryTerrainElevation(lngLat(p))||0)+this.map.getCameraTargetElevation();this.ground.set(p.id,{x:p.x,y:p.y,z,time:now});return z}
  render(matrix:number[]){if(this.disposed||this.getSettings().active===false){this.previous=0;return;}const now=performance.now(),state=this.getState(),{graphics,perspective,selected}=this.getSettings();if(this.previous)this.frames.push(now-this.previous);this.previous=now;if(now-this.report>1500&&this.frames.length){this.onFPS(Math.round(1000/(this.frames.reduce((a,b)=>a+b,0)/this.frames.length)));this.frames=[];this.report=now}
    if(state.time!==this.snapshotTime){this.snapshotTime=state.time;this.arrival=now}const time=state.time+(state.paused?0:Math.min(.1,(now-this.arrival)/1000)*state.speed)
    // MapLibre 4 custom-layer matrices use a target-relative vertical origin; simulation and cached models use sea-level elevations.
    this.transform.elements[14]=-this.map.getCameraTargetElevation()*this.transform.elements[10]
    this.camera.projectionMatrix.fromArray(matrix).multiply(this.transform);this.camera.projectionMatrixInverse.copy(this.camera.projectionMatrix).invert();const counts=new Map<string,number>(),ec=new Map<string,number>(),center=this.map.getCenter(),zoom=this.map.getZoom();this.soldiers.BLU.begin();this.soldiers.RED.begin()
    for(const base of this.bases){
      const side = base.point.id.startsWith('BLU') ? 'BLU' : 'RED'
      if (base.model.name === 'AIRFIELD' && base.model.userData.tier !== state.airfields[side].tier) {
        this.scene.remove(base.model); disposeModel(base.model)
        base.model = createBase('AIRFIELD', side, state.airfields[side].tier); base.model.position.set(base.point.x, base.point.y, 0); this.scene.add(base.model)
      }
      const { model, point } = base
      model.visible=graphics.models&&zoom>12&&Math.hypot((lngLat(point)[0]-center.lng)*93650,(lngLat(point)[1]-center.lat)*111320)<3000;const terrain=!!this.map.getTerrain();if(model.visible&&(model.userData.terrain!==terrain||!model.userData.conformedAt||now-model.userData.conformedAt>6000)){conformBase(model,(x,y)=>terrain?((this.map.queryTerrainElevation(lngLat({x:point.x+x,y:point.y+y}))||0)+this.map.getCameraTargetElevation()):0);model.userData.terrain=terrain;model.userData.conformedAt=now}model.position.z=1.2}
    const liveAircraft=new Set([...state.units.filter(u=>isAir(u.role)||isSupportModel(u.role)).map(u=>u.id),...state.casualties.map(c=>`wreck-${c.id}`)]);for(const[id,model]of this.aircraft){if(!liveAircraft.has(id)){this.scene.remove(model);disposeModel(model);this.aircraft.delete(id)}else model.visible=false}
    for(const batches of Object.values(this.corpseBatches))for(const batch of batches)batch.begin()
    const corpseCounts={BLU:0,RED:0}
    const visibleCasualties=state.casualties.filter(c=>perspective==='OBS'||c.observed.includes(perspective)).map(c=>({...c,id:`wreck-${c.id}`,hp:0,members:0,maxMembers:0,ammo:0,fuel:0,path:[],mission:'DESTROYED',target:'',name:'Wreck',kills:0,subcommand:'',firing:false,spotted:true,soldiers:c.soldier?[c.soldier]:[]} as Unit))
    for(const u of [...state.units.filter(u=>(!u.carrier||u.soldiers?.some(s=>s.disembarked))&&(u.hp>0||u.soldiers?.some(s=>s.status==='downed'))),...visibleCasualties]){if(perspective!=='OBS'&&u.side!==perspective&&!u.spotted)continue;const ll=lngLat(u),dist=Math.hypot((ll[0]-center.lng)*93650,(ll[1]-center.lat)*111320);if(dist>1700&&u.id!==selected)continue;const z=this.altitude(u,now)
      if(isAir(u.role)||isSupportModel(u.role)){let model=this.aircraft.get(u.id);if(!model){model=isAir(u.role)?createAircraft(u.role,u.side):createSupportModel(u.role,u.side);if(u.hp<=0)model.traverse(o=>{if(o instanceof T.Mesh)(o.material as T.MeshStandardMaterial).color.multiplyScalar(.35)});this.aircraft.set(u.id,model);this.scene.add(model)}model.visible=graphics.models;model.position.set(u.x,u.y,z+(u.altitude||0)+.1);model.rotation.set(u.hp<=0?.18:0,u.role==='JET'?Math.sin(time)*.06:0,-u.heading);animateAircraft(model,u.hp>0&&u.engine?time:0);animateSupport(model,time,u.transport);const sling=model.getObjectByName('sling-cargo');if(sling)sling.visible=!!u.transport?.cargo&&(u.altitude||0)>8;const ramp=model.getObjectByName('cargo-ramp');if(ramp)ramp.rotation.x=u.transport?.phase==='unloading'?1.2:0;if(u.transport?.phase==='departed'||u.transport?.phase==='waiting'&&u.role==='CARGO_PLANE')model.visible=false}
      else if(isVehicle(u.role)){const key=`${u.side}-${u.role}`,mesh=this.groups.get(key)!,n=counts.get(key)||0;if(n>=64)continue;this.dummy.position.set(u.x,u.y,z+(u.altitude||0)+.1);this.dummy.rotation.set(u.hp<=0?.18:0,u.role==='JET'?Math.sin(time)*.06:0,-u.heading);this.dummy.scale.setScalar(1);this.dummy.updateMatrix();mesh.setMatrixAt(n,this.dummy.matrix);mesh.setColorAt(n,new T.Color(u.hp<=0?.3:1,u.hp<=0?.3:1,u.hp<=0?.3:1));if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;counts.set(key,n+1);const attachment=this.groups.get(`${key}-attachment`);if(attachment){this.dummy.rotation.z=u.role==='ATTACK_HELI'?time*35:-(u.aim??u.heading);this.dummy.updateMatrix();attachment.setMatrixAt(n,this.dummy.matrix);counts.set(`${key}-attachment`,n+1)}}
      else for(const s of u.soldiers||[]){if(u.carrier&&!s.disembarked)continue;const ground=this.altitude(s,now);if(u.id.startsWith('wreck-')){const index=Math.floor(corpseCounts[u.side]++/400);if(!this.corpseBatches[u.side][index])this.corpseBatches[u.side][index]=new SoldierBatch(this.scene,u.side,new T.MeshStandardMaterial({vertexColors:true,roughness:.9}));this.corpseBatches[u.side][index].pose(s,u.role,time,ground+.05,zoom>17)}else this.soldiers[u.side].pose(s,u.role,time,ground+.05,zoom>17||u.id===selected);const n=ec.get('shadow')||0;if(graphics.shadows&&n<256){this.dummy.position.set(s.x,s.y,ground+.025);this.dummy.rotation.set(0,0,0);this.dummy.scale.set(.65,.45,1);this.dummy.updateMatrix();this.effects.get('shadow')!.setMatrixAt(n,this.dummy.matrix);ec.set('shadow',n+1)}}
    }
    const place=(key:string,x:number,y:number,z:number,sx:number,sy:number,sz:number,dir?:T.Vector3)=>{const mesh=this.effects.get(key)!,n=ec.get(key)||0;if(n>=mesh.instanceMatrix.count)return;this.dummy.position.set(x,y,z);this.dummy.rotation.set(0,0,0);if(dir)this.dummy.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),dir);this.dummy.scale.set(sx,sy,sz);this.dummy.updateMatrix();mesh.setMatrixAt(n,this.dummy.matrix);ec.set(key,n+1)}
    for(const e of state.shots){if(perspective!=='OBS'&&e.side!==perspective&&!e.spotted)continue;const age=time-e.time;if(age<0)continue;const start=new T.Vector3(e.start.x,e.start.y,e.start.z),end=new T.Vector3(e.end.x,e.end.y,e.end.z);if(!graphics.terrain){start.z-=this.altitude({...e.start,id:`s${e.id}`},now);end.z-=this.altitude({...e.end,id:`e${e.id}`},now)}const length=start.distanceTo(end),duration=length/e.speed,p=Math.min(1,age/Math.max(.03,duration)),pos=start.clone().lerp(end,p),direction=end.clone().sub(start).normalize();if(e.weapon==='mortar')pos.z+=Math.sin(p*Math.PI)*length*.22
      if(age<duration){const size=Math.max(e.size,zoom<17?.25:.07);place(`${e.side}-core`,pos.x,pos.y,pos.z,size,size,e.size>.15?1.2:.65,direction);place(`${e.side}-glow`,pos.x,pos.y,pos.z,size*3,size*3,1.1,direction)}else{const impact=age-duration,life=e.blast?1.3:.16;if(impact<life){const r=e.blast?Math.max(.3,e.blast*Math.sin(impact/life*Math.PI/2)):.35;place(`${e.side}-blast`,end.x,end.y,end.z,r,r,r)}}
    }
    for(const c of state.casualties){const age=time-c.time;if(isVehicle(c.role)&&c.altitude===0&&age<24&&(perspective==='OBS'||c.observed.includes(perspective))){const z=this.altitude(c,now);for(let i=0;i<3;i++)place('smoke',c.x+Math.sin(i)*2,c.y+Math.cos(i)*2,z+2+i*2,2+i,2+i,3+i)}}
    for(const s of state.smokes){if(perspective!=='OBS'&&s.side!==perspective&&!state.units.some(u=>u.side===perspective&&Math.hypot(u.x-s.x,u.y-s.y)<600))continue;const age=time-s.time;if(age<1){const p=Math.max(0,age);place(`${s.side}-core`,s.from.x+(s.x-s.from.x)*p,s.from.y+(s.y-s.from.y)*p,s.from.z+(s.z-s.from.z)*p+Math.sin(p*Math.PI)*4,.12,.12,.12)}else{const r=Math.min(12,(age-1)*4)*Math.min(1,(s.expires-time)/4);for(let i=0;i<5;i++)place('smoke',s.x+Math.sin(i*2)*r*.4,s.y+Math.cos(i*2)*r*.4,s.z+3+i,r*.65,r*.65,r*.65)}}
    for(const batches of Object.values(this.corpseBatches))for(const batch of batches)batch.end(graphics.models)
    this.soldiers.BLU.end(graphics.models);this.soldiers.RED.end(graphics.models);for(const[key,mesh]of this.groups){mesh.count=graphics.models?counts.get(key)||0:0;mesh.instanceMatrix.needsUpdate=true}for(const[key,mesh]of this.effects){mesh.count=ec.get(key)||0;mesh.instanceMatrix.needsUpdate=true}
    this.renderer.resetState();this.renderer.render(this.scene,this.camera);this.renderer.resetState();if(!state.paused&&!state.winner&&!document.hidden)this.map.triggerRepaint();if(this.ground.size>1500)this.ground.clear()
  }
  dispose(){if(this.disposed)return;this.disposed=true;if(process.env.NODE_ENV==='development'){const debug=window as unknown as {gridDebug?:BattlefieldRenderer};if(debug.gridDebug===this)delete debug.gridDebug}if(this.map.getLayer(this.layer.id))this.map.removeLayer(this.layer.id);disposeModel(this.scene);this.aircraft.clear();this.bases=[];this.renderer?.dispose();this.ground.clear()}
}
