import supplied from '../../_sfx.json'

export interface OscillatorPreset { enabled:boolean;wave:OscillatorType;freq:number;ratio:number;gain:number;detune:number;endRatio:number;pan:number;phase:number }
export interface SoundPreset {name:string;loop:boolean;vehicle:boolean;duration:number;attack:number;decay:number;sustain:number;release:number;filterType:BiquadFilterType;filterFreq:number;filterQ:number;noiseGain:number;noiseFreq:number;distortion:number;output:number;speedPitchMax:number;speedFilterMax:number;repeatHz:number;repeatSpeedMax:number;repeatDepth:number;oscillators:OscillatorPreset[]}
export type SoundBank=Record<string,SoundPreset>
export const MAX_BANK_BYTES=256*1024
const ranges:Record<Exclude<keyof SoundPreset,'name'|'loop'|'vehicle'|'filterType'|'oscillators'>,[number,number]>={duration:[.01,30],attack:[0,10],decay:[0,10],sustain:[0,1],release:[0,10],filterFreq:[10,24000],filterQ:[0,40],noiseGain:[0,4],noiseFreq:[10,24000],distortion:[0,100],output:[0,4],speedPitchMax:[.05,8],speedFilterMax:[.05,8],repeatHz:[0,100],repeatSpeedMax:[.05,8],repeatDepth:[0,1]}
const oscillatorRanges:Record<Exclude<keyof OscillatorPreset,'enabled'|'wave'>,[number,number]>={freq:[1,24000],ratio:[.01,20],gain:[0,4],detune:[-4800,4800],endRatio:[.01,20],pan:[-1,1],phase:[0,360]}
const waves:OscillatorType[]=['sine','square','triangle','sawtooth'],filters:BiquadFilterType[]=['lowpass','highpass','bandpass','notch','allpass','peaking','lowshelf','highshelf']
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
const validNumber=(v:unknown,[min,max]:[number,number])=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max
const fallbackOscillator:OscillatorPreset={enabled:false,wave:'sine',freq:220,ratio:1,gain:0,detune:0,endRatio:1,pan:0,phase:0}
function oscillator(raw:unknown,fallback:OscillatorPreset):OscillatorPreset{const value=object(raw)?raw:{};const out={...fallback};if(typeof value.enabled==='boolean')out.enabled=value.enabled;if(waves.includes(value.wave as OscillatorType))out.wave=value.wave as OscillatorType;for(const key of Object.keys(oscillatorRanges) as (keyof typeof oscillatorRanges)[])if(validNumber(value[key],oscillatorRanges[key]))out[key]=value[key] as number;return out}
function preset(raw:unknown,fallback:SoundPreset):SoundPreset{const value=object(raw)?raw:{};const out={...fallback,oscillators:fallback.oscillators.map(o=>({...o}))};if(typeof value.name==='string'&&value.name.trim()&&value.name.length<=100)out.name=value.name;if(typeof value.loop==='boolean')out.loop=value.loop;if(typeof value.vehicle==='boolean')out.vehicle=value.vehicle;if(filters.includes(value.filterType as BiquadFilterType))out.filterType=value.filterType as BiquadFilterType;for(const key of Object.keys(ranges) as (keyof typeof ranges)[])if(validNumber(value[key],ranges[key]))(out as unknown as Record<string,number>)[key]=value[key] as number;if(Array.isArray(value.oscillators))out.oscillators=Array.from({length:3},(_,i)=>oscillator(value.oscillators[i],fallback.oscillators[i]||fallbackOscillator));return out}
const raw=supplied as unknown as Record<string,SoundPreset>
export const DEFAULT_BANK=Object.fromEntries(Object.entries(raw).map(([key,value])=>[key,preset(value,{...value,oscillators:Array.from({length:3},(_,i)=>oscillator(value.oscillators?.[i],fallbackOscillator))})])) as SoundBank
export function parseSoundBank(text:string,base:SoundBank=DEFAULT_BANK){if(new TextEncoder().encode(text).length>MAX_BANK_BYTES)throw new Error('Sound bank exceeds 256 KB.');let data:unknown;try{data=JSON.parse(text)}catch{throw new Error('That file is not valid JSON. The active sounds were not changed.')}if(!object(data))throw new Error('Expected a sound preset collection.')
  let replaced=0,ignored=0;const bank={...base};for(const[key,value]of Object.entries(data)){if(!Object.hasOwn(DEFAULT_BANK,key)){ignored++;continue}bank[key]=preset(value,DEFAULT_BANK[key]);replaced++}if(!replaced)throw new Error('No recognized sound events were found.');return{bank,replaced,retained:Object.keys(base).length-replaced,ignored}
}
export function clonePreset(value:SoundPreset):SoundPreset{return preset(value,value)}

