import { isAir, isArmored, type Role, type Unit } from './types'
export interface Weapon { id:string; range:number; damage:number; cooldown:number; armor:boolean; air:boolean; speed:number; size:number; blast:number; sound:string }
const rifle: Weapon={id:'rifle',range:600,damage:3,cooldown:.5,armor:false,air:false,speed:600,size:.055,blast:0,sound:'RIFLE_FIRE'}
const mg:Weapon={...rifle,id:'mg',range:800,damage:3.5,cooldown:.16,size:.11,sound:'MG_FIRE'}
const cannon:Weapon={id:'cannon',range:1400,damage:23,cooldown:3.8,armor:true,air:false,speed:450,size:.26,blast:12,sound:'TANK_FIRE'}
export const WEAPONS:Record<string,Weapon>={casGun:{...mg,id:'cas-gun',range:1200,damage:6,cooldown:.2,speed:800,size:.14},aa:{...cannon,id:'aa',range:2400,damage:65,cooldown:8,air:true,speed:320,blast:0,sound:'AT_FIRE'},rifle,mg,cannon,at:{...cannon,id:'at',range:900,damage:29,cooldown:5,speed:160,size:.2,blast:8,sound:'AT_FIRE'},autocannon:{...cannon,id:'autocannon',air:true,range:1200,damage:9,cooldown:.7,size:.17,blast:5},missile:{...cannon,id:'missile',air:true,range:1800,damage:32,cooldown:4,speed:240,size:.3,blast:14,sound:'AT_FIRE'},mortar:{...cannon,id:'mortar',range:1200,damage:12,cooldown:6,armor:false,speed:90,size:.22,blast:20,sound:'MORTAR_FIRE'}}
export function weaponFor(role:Role):Weapon|null { if(['RECON_UAV','TRUCK','FORKLIFT','CARGO_PLANE','UAV_JAMMER','TRANSPORT_HELI','HEAVY_LIFT_HELI','TROOP_TRUCK'].includes(role))return null;if(role==='LANDING_CRAFT')return null;if(role==='FRIGATE')return WEAPONS.missile;if(role==='PATROL_BOAT'||role==='AMPHIBIOUS_APC')return WEAPONS.autocannon;if(role==='CAS_FIGHTER')return WEAPONS.casGun;if(role==='AA_TEAM')return WEAPONS.aa;if(role==='MG'||role==='APC')return mg;if(role==='AT')return WEAPONS.at;if(role==='TANK')return cannon;if(role==='IFV'||role==='CANNON_APC')return WEAPONS.autocannon;if(isAir(role))return WEAPONS.missile;if(role==='MORTAR')return WEAPONS.mortar;return rifle }
export function eligible(w:Weapon,target:Pick<Unit,'role'>){return (w.id!=='aa'||isAir(target.role))&&(!isArmored(target.role)||w.armor||w.id==='cas-gun')&&(!isAir(target.role)||w.air)}
export function damageFor(w:Weapon,target:Pick<Unit,'role'>,distance:number){return eligible(w,target)?w.damage*(w.id==='cas-gun'&&target.role==='TANK'?.1:1)*Math.max(.35,1-distance/w.range*.5):0}
